### ISSUE TITLE
[Bug] Cannot Upload Custom Preset to Public

### ISSUE THREAD

**Issue by adissadis** [hotosm/osm-export-tool2#103]
# Problem

I found these problem when i want to upload my custom preset in HOT Export by using Presets Page.
 Whenever i tried to check 'Publish this Presets Publicly' , Its always become Private. 

I tried another way by creating HOT Export Job and upload my presets in Presets selection step and check 'Publish this Presets Publicly' to make my presets public. But the result is always same, my preset become private even i already check to make preset public.
# Screenshot

I provide screen shots here:
![image](https://cloud.githubusercontent.com/assets/2520159/10928845/167c3846-82df-11e5-9516-ca0446285b57.png)
The first private preset is by using the Presets Page and the second private presets is by using upload preset in Export Job. Its always uploaded as a private private 
## Question

Is there any step missing from me to upload the preset publicly?

**Comment by mataharimhairi** [comment]
@bjohare This still appears to be an issue, both when loading a preset through the 'Create' process and on the 'Preset' page. I tried various combinations including the saving options on the 'Export Detail's tab at the end of the 'Create' wizard with no luck.

I can see other public presets and am wondering how they managed to make their presets public? This is a pretty important bug. Can we prioritise this above all the other I have been commenting on?

**Comment by bdon** [comment]
new YAML configurations http://exports-staging.hotosm.org/en/v3/#/configurations are all public, will implement setting to private as part of #174
