### ISSUE TITLE
Defaults to HDM Features when Creating New Export with Loaded Preset File

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#104]
I have tried numerous times to upload an 'invalid' preset xml file while creating a new export. Trying to review github issues #92 and #95. Although the job runs fine, the saved custom xml preset file and the listed features on the export details page are from the HDM tree. 

Here's the job http://export.hotosm.org/en/exports/7d1def0c-b73b-4842-8da2-84fc3eec48a3/ . I have also attached the ['invalid'](https://github.com/hotosm/osm-export-tool2/files/27772/invalid_preset.txt) preset file I uploaded (saved as txt file here). Looks as those the data extracted and exported also contains features not listed in the 'invalid' preset file.

**Comment by bjohare** [comment]
Can't reproduce this. Have tried to upload the 'invalid' preset using both the create/clone form and the preset upload form on the presets page. The upload is rejected as invalid as it does not have an xml declaration and is therefore treated as 'text/plain' mime-type. We've implemented it this way to avoid cluttering the tool with 'presets' that are not xml. See https://github.com/hotosm/osm-export-tool2/issues/71#issue-109138473. If the preset upload is rejected then the default model will be HDM.

**Comment by mataharimhairi** [comment]
@bjohare Okay, so that explains why it was defaulting to HDM. Unfortunately there was no error message provided to the UI. I'm guessing this is related to issues #92 and #95. This fix still waiting to go live?

**Comment by bjohare** [comment]
@mataharimhairi yes that fix is live. I get correct error reporting in UI when the file is not a valid xml and when it is not schema valid. Maybe try refreshing your browser cache by pressing F5?
