### ISSUE TITLE
Thematic Export Refinements

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#105]
Issue to address refinements to thematic shapefile exports.

**Comment by mataharimhairi** [comment]
@bjohare What are some of these refinements? Are they linked to some of the other 'High' priority labelled issues?

**Comment by bdon** [comment]
This may refer to the schema of the thematic shps which is hardcoded here: 

https://github.com/hotosm/osm-export-tool2/blob/master/utils/thematic_shp.py#L51

**Comment by bdon** [comment]
The thematic schema has been re-implemented here as a YAML file: 

https://github.com/hotosm/osm-export-tool2/blob/master/feature_selection/examples/thematic.yml

The new format is sufficiently flexible to filter via the old thematic schema and others, so I'm closing this issue
