### ISSUE TITLE
Include PBF in the list of exportable formats

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#109]
It's generated as an intermediate artifact when I choose one of the other export formats. I only want/need a PBF and have no need for another format, so I'd rather avoid generating it.

**Comment by mataharimhairi** [comment]
This would be very useful indeed. And perhaps a .osm file option for those that want to use it in JOSM but don't want to have to install the PBF plugin.

**Comment by mojodna** [comment]
As part of this, it would be great to include metadata and sufficient features to populate the APIDB schema. This means adjusting the Overpass query in use to use `<; >>; >;` (rather than just `<;`) in order to fetch all features referred to by those in the resultset (to satisfy foreign key constraints).

We're currently thinking about using this as the initial provisioning tool for [POSM](https://github.com/AmericanRedCross/posm), so I'm hoping I'll be able to get to this myself in the near future.

**Comment by mojodna** [comment]
Because Overpass produces a .osm file, we can use the same dummy task approach to make it available as a download (and as an individually valid exportable format):

https://github.com/AmericanRedCross/osm-export-tool2/commit/6c7cb5d2220dca8bfc41e1a8ccfa4263d0a4aa7f#diff-826095f95812fdefd41f7fc8c6224f38R216

**Comment by bjohare** [comment]
@mojodna just be aware that the .osm output from overpass is currently not copied from the staging to the download directory. See https://github.com/hotosm/osm-export-tool2/blob/master/tasks/export_tasks.py#L73.  Guess our thinking at the time was to save storage by removing raw osm and providing pbf instead.

**Comment by mojodna** [comment]
@bjohare awesome, I'll remove that and add another shim task to make it available as a downloadable artifact.

**Comment by mojodna** [comment]
Actually, I wound up reverting that change with the same thought you had. Instead, the OSM Export task takes the Overpass query result and runs it through `bzip2` and puts _that_ in the downloads directory.

See #118.
