### ISSUE TITLE
Default to 'My Exports' and 'My Presets'

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#110]
@bjohare the tables automatically display all the 'Exports' and 'Presets' when going to their respective pages. It would make more sense and be much more efficient for them to default to 'My Exports' and 'My Presets' to save time scrolling all the way to the bottom to tick the option.

I assume that most of the users navigating to the Exports and Presets pages have an export or preset in mind, that has most likely be generated by themselves.

**Comment by bdon** [comment]
I have changed it to start with the checkboxes checked. Any revisiting of the UI here should probably wait till we merge in other UI changes.
