### ISSUE TITLE
Colour code 'Next' buttons on 'Create' wizard tabs for better user guidance

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#112]
bjohare commented on Oct 5, 2015
Simplest solution is to disable the 'Tree Tag', 'Preset File' and 'Export Details' tabs until the user has completed the 'Describe Export' and 'File Formats' tabs. I still think there should be a 'Next' button on the 'Describe Export' and 'File Formats' tabs to emphasise the 'wizard' type interface.. ie the user must click though the tabs in order..

bgirardot commented on Oct 5, 2015
I think one of the recent improvements was to add a better error message when you could click create export button, but it would fail, now the error message tells you what is wrong instead of just "invalid" . What I don't understand is when the create button is inactivated, why we can't indicate to the user why it is inactivated.

I am not sure of the need to restrict users from the different tabs or why we would require them to step through tabs in order if we could collect the reasons why we can't create the export and let the user know on that "create export" tab or maybe the tab titles themselves could indicate the tab still needs info filled out like I suggest below. If we do require the user to go through tags in order or can't use some tabs until other are filled out, there probably needs to be an indication of that in the 'tab' display, like turn completed ones green, errored ones red or not accessible ones greyed out or something.

**Comment by mataharimhairi** [comment]
Want to make sure the last comments by @bjohare and @bgirardot are also considered and addressed. Perhaps these could be combined so that a 'Next' button is added to the bottom of the tab in red until all the required actions are completed and then they turn green and can be selected.

**Comment by bdon** [comment]
I've added a "Next" button in the same place as "Skip" for the first two tabs. That should make the navigation a bit more obvious. There are existing red error messages if you can't proceed to the next step yet, highlighting what needs to be changed.

**Comment by bdon** [comment]
This is already on the live site export.hotosm.org
