### ISSUE TITLE
Downloaded Shapefiles only produced three columns (the others columns failed to downloaded)

### ISSUE THREAD

**Issue by adissadis** [hotosm/osm-export-tool2#113]
# Problem

When i want to download HOT Export with my custom presets _that already stored privately_ , it only produce three coloums (osm_id, osm_way_id, and z_index).

![image](https://cloud.githubusercontent.com/assets/2520159/12640022/6bdaf262-c5da-11e5-9650-5bd07778a1a2.png)

_However,_ this bug not appear if you didn't use your custom preset that already stored, instead you upload your custom presets in the last step for creating Job. But, through this step, the data only showed all the generic columns without custom presets columns that need to downloaded.

![image](https://cloud.githubusercontent.com/assets/2520159/12640048/7d545254-c5da-11e5-9a15-273772d59809.png)
# Step to produce this error

Pre-requisite:
You need to upload your custom presets through 'Presets' tab

Step to produce the error:
1. Create a Job through 'Create' tab
2. Select 'OSM Schema' for file format
3. Select 'OSM Data Model' for tree tag
4. Select 'Select Stored Presets' for presets
5. Wait until the job complete and open the data in mapping software (QGIS for example)
6. You will see the attribute of the data only contain 3 columns
# Sample data:

If you interested to see the presets file, you can download it through this link:
https://drive.google.com/open?id=0Bxk-3mw_fhapamhBaEFFS2N0Vnc

**Comment by bdon** [comment]
@adissadis After some investigation I think this is two issues:

1. The supplied Preset is not being parsed correctly and results in too little columns (see #74). 
2. The UI when uploading a Preset is confusing - after opening the File browser to select a Preset XML on your local computer, it still requires one more click to "Upload". If you overlook pressing "Upload" here it defaults to the OSM default model, which is what I believe happened in your second screenshot (observe that the columns do not match that of your preset but are the OSM model). 

Not sure if there is any action to take on this issue in the current code. Both the UI and the filtering/presets are going to be reworked in the current development cycle.

**Comment by bdon** [comment]
The unclear UI around uploading Presets has been replaced with YAML configurations (text instead of XML). Please contact us in the #export-tool gitter or Slack if you need assistance changing things over to the new format.
