### ISSUE TITLE
UI: Bug: Map position on Jobs Page

### ISSUE THREAD

**Issue by jdtoy** [hotosm/osm-export-tool2#12]
The map in the Export Summary section of the `/jobs/` page obscures information, when responsively positioned at certain screen resolutions.

![screen shot 2015-09-02 at 12 20 08](https://cloud.githubusercontent.com/assets/879000/9629841/a9e243f8-516d-11e5-8aa7-4757b0b6e23d.png)

Steps to reproduce:
Visit: http://hot.geoweb.io/en/jobs/5419032f-52bf-4ac0-ad71-1387a2c8ae22/
Set visible screen resolution to 1260px.

Environment:
Chrome: Version 44.0.2403.157 (64-bit)
Mac OSX Yosemite 10.10.2 (14C1514)
MacBook Pro 13 inch

**Comment by bgirardot** [comment]
Curious why this one got closed with no comment, I can confirm it still happens.

**Comment by bjohare** [comment]
Can't reproduce this. Fixed for me on Chrome on Ubuntu, Windows 7 and IE 11 on Windows 7.

**Comment by jdtoy** [comment]
Ah. Cross browser bugs. Yum!
I've updated the issue with details of my environment.
@bgirardot Is your setup similar?

**Comment by bgirardot** [comment]
I do not remember where I first saw it, but I still see it on IE 11, Win 7, but I do not see it on Win 7 chrome or FF. I don't know if the fixes listed above have been pushed to the test site yet or not so I'll try again later.

**Comment by bjohare** [comment]
Changes have been pushed. Maybe try to refresh the page with out touching the cache Ctrl/Shift F5?

**Comment by bgirardot** [comment]
The refresh did the trick for me, I think this one might be fixed @jdtoy what do you see ?

**Comment by jdtoy** [comment]
@bjohare LGTM.

Still a tiny bit of overlap just before the responsive breakpoint, but has resolved the problem totally at my normal resolution.
