### ISSUE TITLE
Adding new export formats to detail.js is very awkward

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#120]
[`ui/static/js/detail.js`](https://github.com/hotosm/osm-export-tool2/blob/master/ui/static/ui/js/detail.js) requires a lot of boilerplate to add new export formats, largely due to things like this [switch statement](https://github.com/hotosm/osm-export-tool2/blob/master/ui/static/ui/js/detail.js#L225). These could be cleaned up to remove boilerplate and repetition.

**Comment by bjohare** [comment]
@mojodna probably should have some display message property on the ExportTask which would just allow simple iteration instead of switch statement. ExportTask's would act more like plugins then which is really how they should work.
