### ISSUE TITLE
{create,clone}.{js,html} are very duplicative

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#121]
There are massive amounts of code and markup shared between the two, some of which has unintentionally diverged (fixes / improvements to one haven't been copied to the other). The HTML could be modularized using Django templating and the JavaScript could...something.

This could be low-hanging fruit for someone wanting to begin familiarizing themselves with the codebase.

**Comment by bdon** [comment]
https://github.com/hotosm/hot-design-system
