### ISSUE TITLE
Automate Development Environment Setup

### ISSUE THREAD

**Issue by ranchodeluxe** [hotosm/osm-export-tool2#122]
A few days ago i tried setting up an `osm-export-tool2` development environment. I came across a lot of the same tricks and trapdoors mentioned in PR #115 . 

I thought it might be useful to automate the creation of a development environment in Virtualbox using Vagrant and Ansbile. Is this something that might be useful to your team? 

Please check out the repository [over here](https://github.com/ranchodeluxe/osm-export-ops). Note, there's still a few kinks to be worked out but it's mostly there.

Cheers

**Comment by mataharimhairi** [comment]
#https://github.com/hotosm/osm-export-tool2/issues/87

**Comment by mojodna** [comment]
A more recent version, worked on by @ranchodeluxe and myself, is here: https://github.com/americanredcross/osm-export-ops

**Comment by mojodna** [comment]
We've moved everything over to Docker and `docker-compose` which makes this easier to develop against and deploy.
