### ISSUE TITLE
Allow input of custom area of interest

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/osm-export-tool2#124]
E.g. input of GeoJSON
and/or search by place name / administrative area name similar to OSM Analytics

**Comment by bgirardot** [comment]
This is a pretty critical enhancement. This enhancement would allow us to generate files based on TM project areas so we could generate the data only for the area that we know has been thoroughly mapped. Having to include data from areas around a TM Project area that have not been well mapped makes the data much less valuable for several use cases.

**Comment by bdon** [comment]
1) Would these need to be persisted in the DB, e.g. saving a "query area", or would pasting in a GeoJSON when creating an export be good enough?

**Comment by mataharimhairi** [comment]
I think pasting in a geoJSON should be sufficient. Especially if users can save and re-run exports with their customised AOIs.

**Comment by bdon** [comment]
Integrated the new AOI selector to new create page.
