### ISSUE TITLE
Export issues (in Haiti); lots of points/lines exported, can't limit to one type of feature?

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool2#130]
Some observations from doing some exports for Haiti (for inclusion in the HDX). These probably apply more broadly. As we'd like to automate these (see #126), we'll need to find a way around both of these. See the test export at http://export.hotosm.org/en/exports/150ae762-eb56-4071-9af6-97281e25c70c/. The preset file only request the following:

```
<item name="Building" type="closedway,relation">
    <combo key="building" values="yes,commercial,residential"/>
    <text key="name"/>
</item>
```

This yields shapefiles with the following:
- A great deal of points and lines? They're nodes like [this church](http://www.openstreetmap.org/node/1167000185#map=19/18.61537/-72.32096), which do have a `name` attribute. These points/lines never seem to get discarded. However, the final export doesn't actually contain the `name` attribute, just geometry and the `osm_id`.
- In the polygon shapefile, also all features that aren't buildings but do have a `name`. Meaning you need to export, then move to QGis for an additional filter step (`building IN ('yes','commercial','residential')`).

The first one seems like a bug to me.

Not sure what to do about the second one, any ideas? As far as I can tell, it's related to using JOSM preset files as a querying mechanism, where you can't really be very specific, for example by querying "I want these features (buildings), and for those features give me the following list of attributes: x, y and z"? Or is there another way to do that currently?

**Comment by mojodna** [comment]
Since presets aren't intended as filters, we'd either need to assume "AND" or "OR" for each key included in an `item`. At the moment, the choice appears to be "OR". Changing that to "AND" could produce a different set of problems.

[`osmfilter`](https://wiki.openstreetmap.org/wiki/Osmfilter) is used under the hood, so we could store a separate filter string (initially derived from the presets) that could be modified to do more advanced filtering that can't be described just by using presets.

**Comment by mataharimhairi** [comment]
Should a different filtering method be applied in general? Say a combination of the tree tag and a key=value combo that could be entered into a text box that pops up when a feature is selected from the tree. 

And the preset capability removed from the Export Tool entirely? I know we were discussing this in Uganda Paul, but you've done a lot more investigating since then and might now see benefits to the preset.

**Comment by PaulUithol** [comment]
Honestly, I think the total number of people able to craft preset files is (and that have taken the trouble to do so) is very low? I get asked to make even the simplest ones for people all the time.. That's just a hunch though; can you see how many people have actually used/uploaded custom preset files?

IMHO, it would perhaps make more sense to standardize around feature selection in the same way as http://overpass-turbo.eu/ does, which is in JOSM nowadays (File->Download from Overpass).

Possibly in the same way as JOSM, which brings what Overpass Turbo calls the "wizard" more to the forefront. Meaning you can use 'simplified' queries (key=value1 AND key=value2), which get translated to a full overpass query, while maintaining the flexibility to adjust either one. We could then call the full Overpass query "advanced mode" and hide it from view entirely, initially?

**Comment by PaulUithol** [comment]
That would ease querying considerably, but still not take care of filtering. Not in favor of changing to `AND`, excluding all buildings without a `name` in the example used here :). Perhaps have a separate input for filtering as an advanced option (expose in UI as well?).

Separate question: why does the export linked here seem to have disappeared? Is this #125 in action?

**Comment by bdon** [comment]
For a revision of the presets functionality I would suggest a YAML or JSON based format. They should be 1:1 translatable with each other. Perhaps a subset of the mapping format Imposm3 uses? 

https://github.com/omniscale/imposm3/blob/master/example-mapping.yml

Extra win if it could be done in a way that we can remove the `tags` table from the database and instead store the preset/mapping in a blob column

**Comment by bdon** [comment]
https://github.com/hotosm/osm-export-tool2/blob/master/hdx/example_preset.yml

proposal for YAML preset format. Notes:

* it handles both AND and OR via a sql fragment
* Thematic Shapefiles: one top level item per theme (one theme has 1-3 shapefiles for points,lines,polygons)
* OSM Shapefiles: 3 shapfiles: planet_osm_point, planet_osm_line, planet_osm_polygon files, each with the union of all attributes specified in preset

for OSM PBFs, PBFs will either be all data or filtered to union of above attributes

Not sure about how this preset maps to Garmin IMG, KML, OsmAnd OBF formats.

**Comment by PaulUithol** [comment]
So for the filtering, I think YAML is definitely much better suited to advanced filtering than the JOSM presets are. Proposal above looks good.

However, it is still mostly suited to advanced users. In addition to that, would it be an option to add a similar syntax to that used in JOSM (Windows->Filter) or the 'wizard' in Overpass Turbo (http://overpass-turbo.eu/)? Or perhaps something even simpler.. 

Examples of that filtering syntax:
- All highways: `highway=*`
- Waterways: `waterway=* | natural=wetland | natural=water | natural=coastline | landuse=basin | landuse=reservoir`
- Buildings that don't have levels or materials: `building=* & ( -building\:levels | -building\:material )`
- Banks and mobile money agents: `amenity=bank or amenity=mobile_money_agent`

**Comment by bdon** [comment]
@PaulUithol Would the existing "Tree tag" GUI in the current Export Tool be sufficient for non-advanced users? 

That could become a GUI that creates YAML behind the scenes. 

I think adding another JOSM/Overpass wizard syntax is doable, but then we would have
1) "tree tag" gui (simple use cases)
2) JOSM/Overpass wizard syntax (medium-advanced users?)
3) YAML (advanced users)

The YAML could also be made more friendly by selecting a pre-existing YAML (just like stored presets) and modifying it in a text area

**Comment by PaulUithol** [comment]
What would be nice is if the tree tag GUI could switch between the GUI, and the ability to modify the generated YAML? I think we're planning on improving the tree tag chooser anyway, isn't it? To get rid of most of the duplication that is there at the moment between "OSM" and "HDM".

**Comment by mataharimhairi** [comment]
#158

**Comment by mataharimhairi** [comment]
#158

**Comment by bdon** [comment]
We've implemented the YAML format and tag tree checkboxes. @PaulUithol this is unidirectional from checkboxes -> YAML, as in you can use the checkboxes to create YAML and then tweak it, but changing the checkbox selections will erase your tweaks. It seemed too complex to make it bidirectional.
