### ISSUE TITLE
Feature Request: Add date/time of most recent database update

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#131]
This question comes up pretty often, how often or when was the last time the database for the export tool has been updated. It would be cool if we could put that info in the menu bar somewhere so it was always visible.

**Comment by bdon** [comment]
This would need to be implemented as part of Overpass, preferably an API call returning an update timestamp, server information etc. There's an open issue here: https://github.com/drolbr/Overpass-API/issues/87

**Comment by bdon** [comment]
We can actually just use the "osm_base" attribute from the Overpass response:

http://overpass-api.de/output_formats.html

This would be a per-export attribute, however, instead of a global one on the website menu bar, but I think that's sufficient for the mentioned use case.

**Comment by mojodna** [comment]
Perhaps we could also ping Overpass with a trivial query on a regular basis and use that as the basis of what's displayed.

**Comment by mojodna** [comment]
@bdon: thoughts on where to stash the return value from Overpass? I don't really want to create a new model to store system-wide metadata, but that might be the most appropriate thing.

(The less-appealing alternative is to have each visitor's browser make an equivalent ping to Overpass and display that using JavaScript.)

**Comment by bdon** [comment]
Every type of output format should have a row in a table; this table should have a column called `extra` or so that is an arbitrary JSON object with information specific to the output format

This would be displayed per-export though. If we wanted it to be system wide maybe store it in an indexable column instead of JSON and just fetch the max value from that column?

**Comment by mojodna** [comment]
Visible on the logged in create + clone pages:

![image](https://cloud.githubusercontent.com/assets/45/24424687/59c67850-13b6-11e7-8d91-87616fdd043e.png)
