### ISSUE TITLE
Ability to change export file formats for an existing export

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#134]
It would be useful to be able to add (not sure about remove) file formats to an existing export. This has come up recently where an export was exactly what was needed except for it did not have the file format needed.

Not sure who should be able to add a file format, but I think just about anyone should be able to as it does not really affect the core of the export, the important parts, just adds one more file format that was not anticipated as being needed.

Hopefully it would encourage reuse of existing exports jobs as well.

**Comment by mataharimhairi** [comment]
This is a great suggestion. More flexibility to modify existing export jobs would be useful and efficient.

**Comment by mataharimhairi** [comment]
Just noticed that its also not possible to adjust tag selection on existing exports when cloning.

**Comment by mojodna** [comment]
That's probably a side effect of #121 where the create and clone functionality are duplicative, but not quite at parity with one another.

**Comment by bdon** [comment]
Right now an Export is immutable. The way to make changes and re-run the export is via the "Clone" functionality which copies all the tag selections, AOI geometry, etc to a new export. While cloning you can add a file format. 

It seems like this feature request is already satisfied via the "Clone" functionality. It might seem lighter weight to modify an existing one in-place just to add one format, however:
* modifying and cloning will take the same amount of time as the raw OSM needs to be downloaded again to perform the conversion
* the new v3 export backend is much faster than before, meaning "cloning" to add one format should be quicker
* it's cleaner for us to always assume that exports are immutable records

**Comment by bdon** [comment]
I'm going to close this issue as I think the Clone functionality handles adding a new export format. Adding a new format requires re-downloading the OSM data from Overpass, so running the whole import process is still necessary. The new export code runs significantly faster than v2, so it should be less time-consuming to clone.
