### ISSUE TITLE
Error: "cannot concatenate 'str' and 'NoneType' objects"

### ISSUE THREAD

**Issue by govvin** [hotosm/osm-export-tool2#135]
I am trying to export data in OsmAnd (OBF), using this export [0] but I am getting an OBF export error. See this screenshot:
![image](https://cloud.githubusercontent.com/assets/5821688/21350227/2b972194-c6f1-11e6-85c5-75e470a0733f.png)

The reason I'm trying to re-create this export is because I've recently noticed than an earlier version I've been using is generating a data file with missing road sections:
![image](https://cloud.githubusercontent.com/assets/5821688/21350259/5e47bc98-c6f1-11e6-978c-0bd568d3eec8.png)

[0]: http://export.hotosm.org/en/exports/41db5476-8338-4f24-90bf-00dcb8a99e09/
[1]: http://export.hotosm.org/en/exports/44df074a-d929-4d9e-b5e6-d8ba9a3670ff/

**Comment by govvin** [comment]
I encountered the same issue again, just now.

![image](https://cloud.githubusercontent.com/assets/5821688/24024989/73e39226-0af2-11e7-8c80-8945286de810.png)

**Comment by bdon** [comment]
@govvin thanks for the report, we are looking into this.

**Comment by bdon** [comment]
Same issue as #129 OsmAndMapCreator doesn't accept duplicate nodes in PBF files, and there is no setting to ignore this. We need to fix our Overpass instance to not output results with duplicate nodes

**Comment by bdon** [comment]
I switched the running instance to use a new Overpass server and reran the OBF export successfully.

@govvin http://export.hotosm.org/exports/41db5476-8338-4f24-90bf-00dcb8a99e09/
