### ISSUE TITLE
Error zipping shape directory; UI should show if no data returned

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#138]
Just ran an export [1] for admin boundaries in Surabaya, Indonesia and received an error for the thematic shapefile:

Error zipping shape directory. Exited with returncode:12

<img width="1208" alt="error zipping shapefile" src="https://cloud.githubusercontent.com/assets/8972913/23495407/7ccaf2c6-ff53-11e6-84e7-c57e886720b0.png">

[1] http://export.hotosm.org/en/exports/9cb4297d-d45f-4fa8-a5c2-289fc3f06285/

**Comment by bdon** [comment]
Is it possible the specified area does not contain any admin boundaries?

**Comment by mataharimhairi** [comment]
Yes. The admin boundaries aren't loaded into OSM for this area yet, which is probably why it is failing but there should be a better way/message provided to the user. Is it possible to return a message saying that there is no data for the selected tags?

**Comment by bdon** [comment]
Yeah, we should display that message, and not show any download options. it's somewhat disappointing to download a PBF or KMZ that's totally empty.

**Comment by mataharimhairi** [comment]
Agreed. If there is a way to differentiate between no data present within OSM to export and a bug in the export tool, and throw that in a message to the user - dev support in the long run would be easier too as we would know the diff quicker.

**Comment by bdon** [comment]
Related: themes should not be only a .cpg and .dbf if the thematic shapefile is empty.

**Comment by bdon** [comment]
Now raising a specific exception when the OSM XML response is empty. I'm not catching it yet to make sure we don't get any false positives.
