### ISSUE TITLE
Add exception tracker.

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#139]
Right now, errors in Celery tasks are saved in the DB and shown in the UI to users. 

Instead, we should integrate a exception tracker like Airbrake or Sentry. This should be more or less drop-in and let the developers know immediately when a job fails. This may also let us simplify the exception handling logic in the tasks.

**Comment by bdon** [comment]
If HOT already has a subscription with one of these services, we should use that. Otherwise I'm a fan of sentry.io

**Comment by mataharimhairi** [comment]
@davidneudorfer Would you be able to tell us if HOT has access to either Airbrake or Sentry.

**Comment by bdon** [comment]
I created a Sentry organization and am logging any exceptions that happen in prod. We can revisit this when we have more plans around our new prod environment and monitoring.
