### ISSUE TITLE
Add a "short" name the export job

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#14]
The files that get generated would be nice if they included a short name. query.shp, query.obf, query.kmz, etc would be much better with a 'short name' in the file name.

**Comment by bjohare** [comment]
Fixed this. Files are renamed by lowercasing, removing non-word characters and replacing whitespace with underscores.

**Comment by bgirardot** [comment]
This sounds like a good idea. I just re-ran an export job but it did not name the files any differently so maybe I can't test it yet. But really I am good with anything that changes the file names to something besides the query.* names so people can more easily work with them.

**Comment by mataharimhairi** [comment]
I created several test exports and the files now take on the 'Name' entered on the 'Describe Export' tab as mentioned by Brian.

So when I enter Dar es Salaam, my exports were named dar_es_salaam_shp, dar_es_salaam_thematic_shp, dar_es_salaam.sqlite and dar_es_salaam.pbf.
