### ISSUE TITLE
Polygon drawing tool enhancements

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool2#146]
The freeform polygon tool requires me to drag to create vertices (at least for me on chrome in windows) but this is difficult with a mouse which is the most common use case.  

Also, if digitizing a region boundary, I would generally zoom and pan while doing so.  However at the moment there are no pan options (to buttons in the interface and arrow keys aren't panning).

**Comment by mojodna** [comment]
Workaround: create a GeoJSON polygon using an external tool like geojson.io and upload that to the tool.

Longer-term, Terranodo (who produced this component in the first place) will be revisiting it, so we're potentially going to hold off until they get a chance to prioritize this.

Adding pan buttons may be another low-hanging fruit way to address this, so I'll look into that.

**Comment by mataharimhairi** [comment]
Just to add a note, that it is also pretty difficult for me to draw the AOI free form at the moment using Chrome on OSX. It doesn't always add a node when I click/double-click. Sometimes I just get lucky after clicking like crazy.

**Comment by mojodna** [comment]
I've found that I've had better luck drawing free-form AOIs by clicking and dragging.

**Comment by bdon** [comment]
from cj:
```
The draw tool for creating a region boundary operates like this:

The first click sets the first vertex
Subsequent clicks have no effect
Dragging creates vertices, and it is impossible to zoom/pan during the dragging operation.
It would be easier to create free form polygons if each click placed a vertex, and zoom/pan operations were allowed between clicks. 
geojson.io has a good example of this behavior with the "draw a polygon" tool.

```

**Comment by bdon** [comment]
http://exports-staging.hotosm.org has been updated with the drawing mode as @cjhendrix described, allows zooming while drawing.

**Comment by cjhendrix** [comment]
Works great!  Thanks!
