### ISSUE TITLE
An modified region didn't create datasets on HDX, but on a second run it did

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool2#148]
1. I opened the existing Gambia region
1. I changed some metadata including changing the name prefix from `hotosm_gambia` to `hotosm_gmb`
1. I changed the region definition via a search for Gambia
1. I changed the schedule to monthly at 2am UTC
1. I clicked `Save + Sync`
1. I clicked `Run Now`

The run (highlighted in the screen cap below) appeared to start and complete, but the datasets *were not* on  HDX demo.   I ran it again this morning (13-apr 8:33 UTC) and it completed and the datasets *were* on HDX demo.

![image](https://cloud.githubusercontent.com/assets/1654485/25003500/fa99633c-204f-11e7-9a7b-1f37ee031298.png)

**Comment by bdon** [comment]
These were failing to update on HDX due to either missing fields in the HDX objects, which we've fixed, or intermittent SSL errors which have also been fixed. Closing this issue for now, re-open if you observe any missing updates.
