### ISSUE TITLE
List of jobs exports, number to list needs adjustment

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#15]
5, 10, or 15 is a pretty limited range, how about 5, 25, 50, 100.

Also, selecting the pop-down to change the number has no effect.

**Comment by bgirardot** [comment]
Actually, now that I have created more jobs, I can see that changing the number to list does have some effect, but it seems a bit bugged. 

In this screen shot, you can see I have 10 selected and it says 7 of 7 displayed.

![2015-09-03_00h31_33](https://cloud.githubusercontent.com/assets/265831/9646368/28bd96f4-51d3-11e5-9e9f-a3ac1f7863e7.png)

Now I have switched it to 15 and it says 8 of 8 displayed:

![2015-09-03_00h32_20](https://cloud.githubusercontent.com/assets/265831/9646377/472bc6ba-51d3-11e5-9569-71d9462588c4.png)

Not sure what is going on there.

**Comment by bgirardot** [comment]
I also think "Page Size" is the wrong label for that pop down. "Lines" or "Exports to Display" would make more sense.

**Comment by bjohare** [comment]
Can't reproduce the pagination issue you describe.. any chance you could try again? Have renamed the pagination label.

**Comment by bjohare** [comment]
Not sure I agree about increasing the pagination size options.. I'm concerned that as more results are displayed  performance will decrease, also the map will disappear from view if 50 exports are displayed per page.. I think we have reasonable pagination and filtering which might be enough??

**Comment by bgirardot** [comment]
could we try a 25? 15 just seems really short to me.

The Pagination issue was fixed yesterday, sorry I didn't mention that, I thought you intentionally fixed it, but maybe it got fixed as part of another adjustment.

**Comment by bjohare** [comment]
Have added 20 and 25 as options. Also will look at making the map div sticky so it remains in place if user scrolls down the export list.

**Comment by mataharimhairi** [comment]
Could we try to keep this consistent across the 'Exports' and 'Presets' pages, perhaps using the following text for both:

'Display Per Page'

The right number of Exports are displayed according to my 'Display Per Page' option, as I changed between 5, 10, 15 and 20.
