### ISSUE TITLE
HDX exports for KML, IMG formats; only create requested formats

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#150]
- [x] Thematic KMLs
- [x] fix non-thematic SHPs
- [x] HDX upload of resources

**Comment by bdon** [comment]
We agreed that HDX will host OSM PBF and Garmin IMG formats.

Given that all files hosted on DHX are thematic, I am trying to understand how best to add these two formats. OSM PBFs are for a region, and not filtered to a specific theme. Also, the Garmin IMG converter works directly off OSM PBF files, so it's also not per-theme. PBFs could be filtered to a specific theme using `osmfilter` but I'm not sure of the use case. @mojodna are there tools that use PBF/IMG that would benefit from data being filtered to a single theme?

**Comment by mojodna** [comment]
IIRC, there are (or were) actually 2 PBFs used in the intermediate processing steps; one with all of the data, one that's been filtered using `osmfilter` prior to being converted into other formats (perhaps the IMG?). The filtered version of the PBF isn't useful other than as an intermediate artifact, the Garmin IMG is useful if it contains "useful stuff" (which probably isn't everything, but I don't know what that subset is).

Does it make sense to have an umbrella dataset for a given export region on HDX with pointers to each of the themes as well as the general-purpose artifacts?

**Comment by bdon** [comment]
An umbrella dataset makes sense to me, that could have each of PBF, IMG, Geopackage, Shapefiles for all themes together. `osmfilter` currently isn't used by the exporters. Making thematic PBFs and IMGs seems a bit contrived.
