### ISSUE TITLE
Create tool to convert JOSM presets to YAML

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#157]
This may not be (probably isn't) a 1:1 conversion, but it represents a starting point for creating YAML-flavored filtering criteria.

**Comment by bdon** [comment]
Referring back to #79 and @PaulUithol 's links, JOSM presets are generally not specific enough to convert directly, without some manual intervention or heuristics. 

As a basic example, consider the Indonesia data model https://docs.google.com/document/d/1ivWj7AfMT4W4m8uymhBLmr7ZQ6YkoaiaqBYODkmrwIk/edit

for the "Banks" theme, the JOSM preset defines possible values for amenity, building, building:levels, addr:full tags. But that isn't enough information to filter OSM data - you'd need to be familiar with OSM tagging conventions = the right filter is probably `amenity='bank' OR building = 'bank'` and the rest of the tags are optional.

**Comment by bdon** [comment]
OK, I have a complete understanding of this now and have created a basic form that lets one paste (upload?) a JOSM preset XML and outputs a YAML feature selection. The details:

- The vast majority of saved presets from the old export tool are subsets of the HDM and OSM data models.
- a JOSM preset can have arbitrarily nested `group`s, thus there isn't anything directly corresponding to themes. I guessed at themes by finding the shallowest level of `groups` with more than one element. 
- JOSM preset group names can be unicode names with diacritics, need to convert to ASCII for theme names in Shapefiles/other formats.
- The set of all `key`s within a Preset's `group` determines the `keys` selection in the YAML, this is straightforward. Similarly the set of all `types` determines the YAML `geom_types`.
- The YAML `where` is tricky and is the source of some past confusion mentioned in github issues. I am automatically creating a SQL OR which is like this:

    building=residential OR building=stadium OR building=synagogue OR building=mosque OR
    building=church OR building=house OR building=industrial OR building=school
    OR building=yes

This will limit the theme to ONLY OSM elements that match one of the josm preset tags. In most cases this will be sufficient but in some cases it will be too general. Another approach would just be having `building IS NOT NULL or other_key IS NOT NULL`, this may not be general enough. Either way there is some interpretation necessary to determine what the user actually wants in that theme.

**Comment by bdon** [comment]
A barebones version of this is here: http://exports-staging.hotosm.org/en/v3/#/hdx/preset_to_yaml

I'm thinking either have a page to convert presets like this, or in the "Create exports" workflow, allow a place to upload a Preset

**Comment by bdon** [comment]
This has been implemented for the "planet_osm" schema, but not for the "Thematic Shapefile" schemas.

**Comment by bdon** [comment]
This works in Chrome, Firefox and Safari, but not Internet Explorer. It doesn't work because IE does not implement the DOM Level 3 XPath API. If we want it to work in IE we need a polyfill or use a different library like WGX.
