### ISSUE TITLE
Include boundary used for clipping alongside HDX artifacts

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#159]
In some cases this will be an admin boundary (or an approximation of one). This is to be included for use by those who wish to use other tools to further clip (vs. buffered clipping) HDX datasets and want to have something consistent. Format: either Shapefile (with 1 feature) or GeoJSON.

(We'd also talked about creating a separate HDX dataset containing only clipping boundaries, but I think we settled on only including individual boundaries alongside their corresponding data for now, citing confusion and complexity of managing such datasets.)

**Comment by bdon** [comment]
I'm including this as a "boundary" layer in Geopackages. 

Should this be only for HDX downloads or all export tool downloads in general?

**Comment by mojodna** [comment]
I would say "anything that's clipped" should include this. The current AOI selector only does bounding boxes, but once we move the new one in, anything could be clipped. Perhaps the bounding box geometry is worth including no matter what.
