### ISSUE TITLE
Currently available areas for export jobs is too limited

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#16]
The currently supported areas for export jobs is too limited and doesn't cover a lot of the island chains east of the Philippines.

Also, how hard is this to adjust, one of the design goals of the redevelopment was supposed to be it was easier to adjust the available areas, but I do not see any indication of how to do that.

**Comment by bjohare** [comment]
Regions can be added and areas modified in the Admin interface.

**Comment by bgirardot** [comment]
Sounds good.
