### ISSUE TITLE
Signup flow may be unreliable; migrate to new socialauth and expose permissions via API

### ISSUE THREAD

**Issue by mojodna** [hotosm/osm-export-tool2#161]
When signing up to access the new staging site, @bdon had to go through the "enter your email address" flow twice (the second time after clicking a verification link) in order to show up in the admin interface (and presumably to have a full account on the site).

Amadou may have also run into this prior to being granted permissions to access the HDX UI.

I haven't personally experienced this, but would like to continue to keep an eye out for other related weirdness.

**Comment by ndongamadu** [comment]
The link in the verification automatic email is not pointing to osm2hdx but to the main HOT Exports tool staging environment.

**Comment by mojodna** [comment]
This is expected, as the verification email is intended for all Export Tool users.

**Comment by bdon** [comment]
We should upgrade to https://github.com/python-social-auth/social-app-django as our current social auth plugin is buggy and deprecated.

**Comment by mojodna** [comment]
Permissions API endpoint added in 01a87a8e2364d6f6d58be686607372db03cf25d7.

Upgraded social-auth in 9556dda10dd78490d6799c818cfa3df02d365044 and 1c338e53add24a9f1714f8929ac66131987fa150.
