### ISSUE TITLE
Export to mbtiles format

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool2#165]
We've been having troubles finding a good way to export OSM data to mbtiles format for a while now (I was actually still using tilemill...). @lusdavo pointed out to me that http://export.posm.io possesses this functionality! Is it part of the current scope/work to port this back to the main instance?

**Comment by mataharimhairi** [comment]
Yes! We've been using POSM to create MBTiles for surveying in Indonesia with OMK. So much easier than getting the team set up with the command line. We are definitely going to be looking to bring that in.

**Comment by mojodna** [comment]
MBTiles archive creation is somewhat fragile for a couple of reasons, which is part of why it ended up folded into the POSM Export Tool instance. Creating archives on individual computers requires specific Node versions and dependencies installed and can be problematic when not on a stable network connection.

Moving MBTiles generation to the cloud helps with both of those problems. However, upstream problems with tile providers (rate limiting or performance issues) can/will delay the task pipeline (affecting non-MBTiles tasks).

We can mitigate this somewhat by limiting the number of tiles that can be mirrored as part of an individual job (a function of bounding box + zoom range). We may be able to mitigate further by providing a dropdown of whitelisted tile sources to guide users in the direction of less-intrusive behavior. A more complicated approach could be to run archive generation in a different Celery queue, although this is more difficult after merging job components to bypass Celery chord management.

**Comment by bdon** [comment]
A multiple queue or priority queue system should be feasible even if we aren't using celery chords.

**Comment by mataharimhairi** [comment]
After discussing, the MBTile file format will be added to export tool V3. This will only work for OSM data and not satellite imagery, like the POSM version does. @mojodna @PaulUithol

**Comment by mojodna** [comment]
This has been deployed to staging.

The tile count is currently limited to 5000 tiles (https://github.com/hotosm/osm-export-tool2/blob/master/ui/app/components/ExportForm.js#L27) to prevent performance degradation.
