### ISSUE TITLE
Geopreviews not always showing up

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#170]
@mataharimhairi did the SHP only dataset you ran create a geopreview successfully?

**Comment by mataharimhairi** [comment]
Been trying to run a only shp file export on Swaziland, which has been running all day! Not sure how to kill it either.

**Comment by mataharimhairi** [comment]
@bdon Removed the Swaziland Export Region and created a new one. It ran and Geopreview successfully displayed the features for the shapefiles.

**Comment by bdon** [comment]
@mataharimhairi what was the name of the one that was running all day? I only see a run for hotosm_swaziland_* (https://demo-data.humdata.org/dataset/hotosm_swaziland_roads ) which completed in 5 minutes

**Comment by bdon** [comment]
This should work now, Although I'm still running into an issue where if there is more than one Shapefile on a dataset (say, lines + polygons) only the first one has a geopreview rendered. It should be that all attached Shapefiles are rendered and the selector in the top right of the map on HDX can switch between them.

**Comment by cjhendrix** [comment]
I believe this is an issue on the HDX side and is being worked in the current sprint.

**Comment by bdon** [comment]
I don't think there is anything actionable on the Export Tool side to address this - closing
