### ISSUE TITLE
HDX Regions List Page Very Slow

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#172]

**Comment by bdon** [comment]
@mojodna I think this is due to the serialization of an export region including the entire geometry. Would it be possible to make the list page only render a bounding box?

**Comment by mojodna** [comment]
And/or N+1 queries for associations, but that's much less likely.

**Comment by mojodna** [comment]
`Job` objects were being serialized as children and including duplicate copies of the geometry. I added a `SimplestJobSerializer` that includes only `uid` and `name` fields which removes that duplication and reduces the number of queries that need to be made to fetch properties.

`HDXExportRegionViewSet` also pre-fetches jobs and related tasks, resulting in fewer queries being executed as well.

I also enabled gzip compression.
