### ISSUE TITLE
Organise/Filter/Paginate HDX Export Region, Exports, Configurations, Configurations(Create page)

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#174]
How are the export regions in the OSM2HDX organised. And can they be searched/filtered. This will become necessary as the created datasets increase. The map shows export areas visually, but does not seem interactive. It would be great if the user could select the region on the map to filter datasets.

**Comment by bdon** [comment]
I think they're organized by internal ID right now which is chronological. We should add pagination (the refactor of the export tool UI will address this as well)

**Comment by mataharimhairi** [comment]
Okay great. I'll relabel this issue so we remember to address it during the refactoring of the frontend. Thanks!
