### ISSUE TITLE
Make Geopackages pass GPKG Validator

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#178]
https://gitlab.com/GitLabRGI/swagd-geopackage-verifier

Small differences in column types of metadata tables

**Comment by bdon** [comment]
Corrected type of zindex from INTEGER(4) TO SMALLINT, as INTEGER(4) is not a valid Geopackage type

**Comment by bdon** [comment]
Other GPKG validation issues seem to have been fixed upstream in GDAL 2.2, although we're still on 2.13 from ubuntugis-unstable

**Comment by bdon** [comment]
The GPKG validator failures don't seem to affect opening in QGIS. Nothing to be done here until we can get a newer binary GDAL release.

**Comment by mojodna** [comment]
https://github.com/mojodna/docker-gdal22 may be of-interest as a base package, as it's built on Ubuntu 16.04.
