### ISSUE TITLE
Select area to export cancellation box in upper right hand area doesn't do anything

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#18]
When I click on the select area to export button another button (?) that says "Select Area to Export X" looks like I can cancel the selection process, but clicking on it to cancel doesn't do anything.

**Comment by bjohare** [comment]
This is a validation indicator. Have removed the 'X' to avoid confusion.

**Comment by mataharimhairi** [comment]
This is really nick-picking, but could we remove apostrophes for any pop-up help text that comes up including this 'Select area to export.' info that comes up on the map. Cheers!

Oh yes, and the 'X' is no longer there.
