### ISSUE TITLE
Add Information on Login Page about HDX and Tasking Manager; redesign landing page

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#180]
We should update the login page, or have a pop up window providing information about datasets on HDX.

**Comment by bdon** [comment]
We should mention Tasking Manager in the same place #166

**Comment by mataharimhairi** [comment]
Agreed. The overall amount of text on the Login page needs to be revised/reduced. Too much text at the moment. And there probably no longer needs to be a link to the original Export Tool.

**Comment by mataharimhairi** [comment]
Landing page redesign: https://exports-staging.hotosm.org/en/v3/
