### ISSUE TITLE
Format titles of datasets created on HDX

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool2#189]
The dataset titles are automatically generated from the "dataset name" field concatenated with the first line of the YAML theme (i.e. `points_of_interest`).  However these theme names do not make good titles as they have to be lowercase and using underscores instead of spaces. 

The YAML "name" key can be used to override the name, however this also overrides the concatenation.  

Could we change the YAML processor to require a "name" key, and create dataset titles from the concatenation of the "dataset name" field and the "name" key?  The YAML should be changed to have space-separated, title-cased theme names: ("Points of Interest", "Roads", "Buildings", "Waterways")

The advantage of this is better looking titles while maintaining standardization across regions.  The disadvantage is that we will no longer be able to override the concatenation with the "dataset name" slug, but I think this is minor.

**Comment by cjhendrix** [comment]
Alternatively, I guess you could change the code to accept YAML theme names with spaces and capitals.

**Comment by mataharimhairi** [comment]
Also thought that the final dataset naming convention looked a little 'untidy' during development, but didn't want to overload deliverables. Ideally it would be great if the code accepted YAML theme names with spaces and capitals, but I'm not sure if this is possibly? @bdon

**Comment by bdon** [comment]
I like the idea of allowing capitals and spaces for the theme names. These would then be "slugified" into lower case + underscores for the dataset URL and export format table names

**Comment by cjhendrix** [comment]
@bdon Any estimate on when this could be done?  I think this is the only blocker to adding more countries.   I don't want to create a lot of new datasets that will have to be edited individually later.

**Comment by bdon** [comment]
@cjhendrix I just put #188 #189 #190 on http://exports-staging.hotosm.org - can you give it a try? if it all looks good i'll put it on prod

**Comment by cjhendrix** [comment]
@bdon Sorry!  I missed this message somehow.   Will test today!
