### ISSUE TITLE
Exports jobs list, clicking on job bounding box in map, doesn't indicate which job is selected in the text list

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#19]
If I see a job I want to run on the map, and I click on the bounding box, it turns blue, but is not highlighted in the list to the left, nor can I double click on it on the map to go to that job to run it.

**Comment by bjohare** [comment]
Fixed highlighting issue. Added double click handler to redirect to export detail page so job can be cloned or run.

**Comment by bgirardot** [comment]
This works for me now and the double click is a great addition
