### ISSUE TITLE
Migration and comms plan from export tool v2 to v3

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#192]
- Notify users of new version
- How long should we have both versions running?
- Contact point for missing functionality from new version - e.g. a user of the v2 export tool has a certain preset or schema that they can't or don't know how to reproduce with the new filtering

@mataharimhairi

**Comment by bdon** [comment]
remove this repo: https://github.com/hotosm/hot-exports

**Comment by mataharimhairi** [comment]
@mojodna @bdon we should create a screencast of how to use the export tool v3. once the mbtiles and OSMAnd file formats are added

**Comment by mataharimhairi** [comment]
#227

**Comment by mataharimhairi** [comment]
A blog will be posted on the hotosm.org website outlining the differences between V2. and V3. on Monday 18th September. The post will contain a community webinar date (mid November) to show case the new tool, as well as provide the screencast showing how to use V3. 

The post will be circulated via the mailing list and tweeted to try and reach as many people as possible.

**Comment by mataharimhairi** [comment]
Communication Plan doc:
https://goo.gl/mFAyJV
