### ISSUE TITLE
delete old run downloads from filesystem

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#193]
This needs to be handled differently for HDX exports as well

**Comment by mojodna** [comment]
Just ephemeral data (`/mnt-storage/stage`), right?

**Comment by mojodna** [comment]
Err, maybe not. `downloads` currently takes up 21G, just for HDX exports and the occasional test run.

**Comment by bdon** [comment]
Including `/mnt-storage/downloads`, I think the old one was after 2 weeks? In the case of HDX, the old downloads should be deleted once a newer run is successfully updated in HDX - i added a flag called expire_old_runs to the Job model to differentiate this without having to refer to the HDXExportRegion model
