### ISSUE TITLE
Updating metadata on HDX also updates the "dataset date"

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool2#197]
The `dataset date` field refers to the data of the resource.  In the case of OSM extracts, this should be the date on which the extract was created or updated, and not the date of any update to metadata.  

In other words only an export run should trigger a change to `dataset date`. 

However, updates to metadata without an export run are unusual, and will be rare once the initial development settles down, so I'm marking this one low priority. 

![image](https://user-images.githubusercontent.com/1654485/27277632-2495ec3c-54df-11e7-8f76-6c5d5f0fb77a.png)

**Comment by bdon** [comment]
In fact this should probably be the Overpass timestamp of the export run, which represents the point in OSM history at which the export run happened.

**Comment by cjhendrix** [comment]
Yes that sounds right.

**Comment by bdon** [comment]
Now the timestamp is only changed when resources are being updated.
