### ISSUE TITLE
Run out of memory when multiple big exports run

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#201]
Investigate a way to solve this. Easiest is to limit concurrency to 1 for certain known big exports like HDX countries.

**Comment by bdon** [comment]
a stopgap solution could be adding swap

**Comment by mojodna** [comment]
27GB of swap added (ephemeral disk).

**Comment by bdon** [comment]
HDX Indonesia is causing Overpass to run out of memory as well

<remark> runtime error: Query ran out of memory in “recurse” at line 1. It would need at least 2049 MB of RAM to continue. </remark>

**Comment by mataharimhairi** [comment]
Some HDX exports are still failing. Brandon has added additional logging from Data Dog, to include all error messages provided from Overpass.

**Comment by bdon** [comment]
We're now actually seeing this: 

'<p><strong style="color:#FF0000">Error</strong>: runtime error: open64: 0
  Success /osm3s_v0.7.54_osm_base Dispatcher_Client::request_read_and_idx::timeout. The server is probably too busy to handle your request.\n', ' </p>\n', '\n', '</body>\n', '</html>\n']
(1 additional frame(s) were not displayed)

when a bunch of runs start simultaneously. We can consider just re-trying if we get this specific error.

**Comment by bdon** [comment]
Look into staggering times to not be on the hour

**Comment by mmd-osm** [comment]
If you've plenty of memory in your box, you can both

- increase the maximum size allowed to a query via [maxsize:...] setting
- increase the overall available memory available to _all_ queries via osm3s_query --space parameter 

 See osm3s_query usage help:
  --space=number: Set the memory limit for the total of all running processes to this value in bytes.

**Comment by bdon** [comment]
@mmd-osm thanks for the tips, incredibly useful. I've subscribed to the overpass-dev mailing list as well. It looks like our best bet may be to ourselves limit the # of simultaneous large requests to Overpass.

**Comment by bdon** [comment]
Changed to run scheduled jobs in serial
