### ISSUE TITLE
Increase size limit to 5000000 sq km

### ISSUE THREAD

**Issue by cjhendrix** [hotosm/osm-export-tool2#206]
DRC and Colombia can't be created because their bounding box size is larger than the 3million sq km limit.

**Comment by cjhendrix** [comment]
To get Indonesia to work, we'd have to increase it to 11 million.

**Comment by bdon** [comment]
I have removed size limits for HDX regions. It should be fine for Indonesia etc, larger regions in areas with more OSM data like North America and western Europe may stall however, so some discretion is needed
