### ISSUE TITLE
Add Feature Search Box to Tree Tag Functionality

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#21]
It is rather tedious to click every + or - if I have to explore the tree looking for something.

**Comment by mataharimhairi** [comment]
Someone did mention potentially having a search text box to look for tags, but I'm assuming that those that are unfamiliar with the features would like to go through all the options.

And the more experienced familiar users will eventually know which branches they need to go to for their specific tags. I suggest we leave this as it is, as there are currently more pressing matters to iron out before the live release?

**Comment by mataharimhairi** [comment]
Will rename this issue to 'Add search box for to tree tag features', as a request for a future enhancement. This will probably become necessary as the tags are reviewed and more are added.

**Comment by mataharimhairi** [comment]
#158 Tag Tree-esque UI for editing YAML-flavored filtering criteria

**Comment by bdon** [comment]
This has been implemented, including alternate search terms, e.g. searching for "river" will display the "Bodies of Water" result

![2017-06-26 12_08_44](https://user-images.githubusercontent.com/77501/27548919-7124cfb2-5a68-11e7-92fa-e327f66b8a05.gif)
