### ISSUE TITLE
Create Partners and Contributors Page

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#211]
Need to add 'Partners and Contributors' to the About Page, similar to OpenAerialMap:

http://openaerialmap.org/about/

<img width="812" alt="screen shot 2017-07-28 at 16 15 46" src="https://user-images.githubusercontent.com/8972913/28711061-728feeb6-73b0-11e7-990d-ddc350fdfdff.png">

Donors include Hewlett Foundation, USAID, Pacific Disaster Centre and potentially more. Let me just confirm that it is fine to add their respective names to the tool first.

**Comment by bdon** [comment]
Sure! could we also get each of their logos preferably in .SVG format?

**Comment by mataharimhairi** [comment]
This has been added to the Landing/About page:

https://exports-staging.hotosm.org/en/v3/

Just need to get final sign off from partners before going live.
