### ISSUE TITLE
Share Tool Website Documentation Skeleton 

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#212]
Can you please share the skeleton and/or working document for the Export Tool online help documentation. 

Would like to share it with the community for feedback and input. Will help us ensure that all the key sections are covered.

We should also review the way it is currently structured and try to take influence to the layout of OAM: 

https://docs.openaerialmap.org/

**Comment by bdon** [comment]
It's live here http://exports-staging.hotosm.org/en/v3/help

I've mostly been working on the Formats page http://exports-staging.hotosm.org/en/v3/help/export_formats

Thanks for the pointer to the OAM docs, I will adjust the layout to match.
