### ISSUE TITLE
Some Selections Lost When Cloning

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#213]
It appears that the 'Project' field on the Describe Export tab, and the feature selection from the tree tags are lost when cloning an existing export.

**Comment by mojodna** [comment]
The `project` field is persisting locally; I don't think we've deployed the fix yet.

The feature selection YAML does persist when cloning but doesn't trigger appropriate checkboxes within the tree. This is confusing but it doesn't appear that anything is lost right now.

**Comment by bdon** [comment]
The checkboxes persisting will require some thought. If the definition of the tag tree changes, any checkbox selections saved in the past won't reflect in the newest tag tree UI. 

This problem would persist even if we saved the checkboxes into the database instead of turning them into YAML.

**Comment by mataharimhairi** [comment]
Solution when cloning an export was to default onto the YAML on the Select Features tab, so that users would see that the original feature selections were still there, as YAML instead of on the tree. YAML will be overwritten when new selections are made using the tree, with previous options needing to be selected again.
