### ISSUE TITLE
Update HOT Logo and Tool Name

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-export-tool2#217]
@mataharimhairi let's update the logo in the top left corner/header to show the actual name, similar to what we're doing with the new Tasking Manager design: http://tasks-demo.hotosm.org/

So it will be the standard HOT logo followed by "Export Tool" in gray. Thanks!

**Comment by mojodna** [comment]
What font is used for "HOT Tasking Manager"? Is that part of the branding, or should it match the site (Open Sans)? Ditto for the grey.

![](http://tasks-demo.hotosm.org/assets/img/tm3_logo.png)

Is there an SVG version of the logo without text? All of the ones in https://drive.google.com/drive/u/0/folders/0B1EorbpNCZ03fmhOV2wtcnVDQ1hsb3o5bXl4Sm8tTUpWUjVKeS1kNHB4TGVSb0t2Q0pISTQ include text? (I can make one, but I'd rather not make yet another.)

**Comment by cgiovando** [comment]
Not yet part of the general branding guidelines - that has been delayed - but yeah, we should use the same font. @bgirardot: is there a version of the logo without text?

cc: @vannicer

**Comment by mataharimhairi** [comment]
@cgiovando Will the TM font change to just 'Tasking Manager', removing the 'HOT' following the logo? Just want to make sure we are all aligned!

**Comment by cgiovando** [comment]
I would say yes - @TylerRadford @smit1678 can you confirm?

@bgirardot can you please provide vector formats for the current TM logo and title, so we can adapt for other tools?

**Comment by TylerRadford** [comment]
I agree. Let's go with the HOT symbol followed by the name of the tool either "Tasking Manager" or "Export Tool" and not repeat "HOT" in the text next to the symbol.

Some guidance is here on the typography but Vizzuality did not get to the point of actually creating vector files. https://drive.google.com/a/hotosm.org/file/d/0B0qNVunoiiLmZUJVd0NMQy05U3c/view?usp=sharing

The suggested typography is open source font 'Yantramanav'

**Comment by DylanMoriarty** [comment]
I tried a few different variations on what's been collectively agree on here:

<img width="809" alt="screenshot 2017-08-28 13 36 17" src="https://user-images.githubusercontent.com/9341928/29785427-89b7c35e-8bf5-11e7-9e99-5ead679d1b53.png">

<img width="612" alt="screenshot 2017-08-28 13 43 36" src="https://user-images.githubusercontent.com/9341928/29785726-a6cdca8c-8bf6-11e7-9212-f5d4f5060ba0.png">

Overall, matching the height of the tool name goes pretty far with making it look more cohesive. Of these, I dig the darker of em', which uses a dark red.

In use:

<img width="789" alt="screenshot 2017-08-28 13 41 29" src="https://user-images.githubusercontent.com/9341928/29785610-3c0049aa-8bf6-11e7-87b5-8b8088d7654c.png">

Granted, I'm cheating a little there by adding a divider line between the logo and nav items. Though, imo we should add one so the logo doesn't conflict with the individual items.

**Comment by DylanMoriarty** [comment]
For anyone who wants to tinker with that, here's a zip with the .ai, .svg, & font files:

[hot-tool-logo.zip](https://github.com/hotosm/osm-export-tool2/files/1257704/hot-tool-logo.zip)

**Comment by mataharimhairi** [comment]
Thanks for trying out some different options @DylanMoriarty. Agreed with the consistency across HOT tools and not repeating the word 'HOT' in the name. For the Export Tool, it should simply be the HOT Logo followed by the text 'Export Tool':

<img width="415" alt="screen shot 2017-08-30 at 12 12 56" src="https://user-images.githubusercontent.com/8972913/29890507-b058536a-8d7c-11e7-8c32-ccf761bc5ce3.png">
