### ISSUE TITLE
Boxes of different sizes in learn page

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-export-tool2#218]
Wondering if we can make them all the same size?

https://exports-staging.hotosm.org/en/v3/learn

Another option would be to have longer horizontal boxes for vertical scrolling? Is the user expected to explore/use them in sequence, or random order?

**Comment by bdon** [comment]
They are the same size in the OAM docs because the content (length of sentence) is uniform across all the boxes. I removed some of the links in the boxes to make them the same size in the Export Tool docs.

**Comment by bdon** [comment]
updated on https://exports-staging.hotosm.org/en/v3/learn

**Comment by cgiovando** [comment]
Thanks @bdon - wondering if we can just set a fixed size, independent of the content. At the moment the second line of boxes is shorter, just because those only have two lines of text. I'm not a web design expert, so whatever you think it's best from your experience. Thanks!
