### ISSUE TITLE
Change Hewlett Foundation Logo

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#219]
The Hewlett Foundation have a new logo that should be used on the 'Landing/About' page. Please find the guidelines and logos available from the following site: http://hfstyleguide.webflow.io/logo

The logo should still be grey scaled and we will double check with a representative from the foundation whether or not it is appropriate.

**Comment by mojodna** [comment]
> While in color, the logo should always appear on a white background. A reversed or white and black logo can appear on solid colors within the brand palette AND on white and black backgrounds.

I pulled the black on white logo from their branding page.
