### ISSUE TITLE
Select Features tab - Annotate has a + but nothing expands when clicked

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#22]
OSM -> Annotation shows a + but nothing expands when clicked

**Comment by bjohare** [comment]
See #23

**Comment by bjohare** [comment]
Added some source annotations but needs to be checked.

**Comment by mataharimhairi** [comment]
The source annotations are now present in the OSM Data Model tree. I went through all of the branches down to their lowest levels and all the branches that have a + symbol contain feature tags.
