### ISSUE TITLE
Inconsistent behavior to display hydrants - using OBF generated by HOT export vs official OsmAnd database

### ISSUE THREAD

**Issue by govvin** [hotosm/osm-export-tool2#224]
Initially, I thought of filing this ticket in OsmAnd, but the app behavior works as expected with the officlal databases, and only acts differently with OBF files generated by [HOT Export Tool](http://export.hotosm.org/en/exports). The objective is display hydrants in OsmAnd as such:
>![image](https://user-images.githubusercontent.com/5821688/29700722-b4499772-8999-11e7-83f3-e5fafd89af4a.png)
>displaying hydrants in OsmAnd as such:

What version of OsmAnd are you using, on what device and Android/iOS version? **Osmand~ 2.7.5 on Android 5.0**

Do you use the offline maps offered within the OsmAnd app for download, or online (tile / raster) maps? **Offline**

If you have an issue related to offline maps, tell us the exact name of the map file where the issue occurs, and its edition date. **Philippines, June 1, 2017** from OsmAnd. 

For reference, I used [this](http://export.hotosm.org/en/exports/04ea1f09-7422-4093-826a-5019f7d1a8bf/) particular export for testing in this ticket.

To display hydrants using the regular offline database from OsmAnd, the user does Menu > Configure map > POI  > select Custom Filter > select Custom Search > select Emergency infrastructure > check on Fire hydrant > Apply > Show. This behavior is correct, as should be expected from the app.
>![image](https://user-images.githubusercontent.com/5821688/29700738-c7e8d590-8999-11e7-8a46-e1675160426f.png)
> Custom filter options when using official OBF

However, this procedure will not work with OsmAnd databases generated by the HOT export tool. It will report "Nothing found:(". To display these hydrants, a user does the following instead:  Menu > Configure map > POI  > select Custom Filter > select Custom Search > **enable** Emergency _(turn everything on for Emergency )_ > Apply > select Emergency infrastructure >  check on Fire hydrant > Apply > Show.

>
![image](https://user-images.githubusercontent.com/5821688/29700814-32632fba-899a-11e7-8d98-e43b040497b7.png)
> Custom filter options when using OBF from HOT exports

In the official instance, the user only needs to select hydrants from the infrastructure category. In the HOT export instance, a user must enable two categories: Emergency, and then select hydrants from Emergency infrastructure.

**Comment by mataharimhairi** [comment]
Hello @govvin. Thank you so much for logging this issue. It appears that you are using an older version of the Export Tool. We are currently in the testing phase of a new release and would greatly appreciate if you could test out the issue on it and report back if possible? Staging for the new version can be found here:  https://exports-staging.hotosm.org/en/v3/

**Comment by govvin** [comment]
Hello @mataharimhairi 

I just tried v3 but the [export](https://exports-staging.hotosm.org/en/v3/exports/c86d6619-1f7b-4909-bf2f-7bd4f1a85579) I made seems to be just running forever. ;)

**Comment by govvin** [comment]
Kindly disregard my previous message. It's just slower than I thought it would be. I'm going to test the OBF I've just exported.

**Comment by mojodna** [comment]
It looks like it eventually finished: https://exports-staging.hotosm.org/downloads/e32b98c9-642d-486e-9a2a-32f58f0ca677/davao-city-and-vicinity_Osmand_2_obf.zip

I was redeploying staging while you ran that, so that might have been part of the problem.

**Comment by govvin** [comment]
Hello again. 

I'd like to report that everything appears to be working as expected with exports made using version 3. The behavior for displaying the POIs are now the same as a user would do with the official OsmAnd OBF files.

**Comment by mojodna** [comment]
Hurrah!
