### ISSUE TITLE
Internet Explorer - page not loading?

### ISSUE THREAD

**Issue by bdon** [hotosm/osm-export-tool2#225]

**Comment by mataharimhairi** [comment]
Has the tool been tested on all top 5 browsers? Firefox, Chrome, Opera, Safari, and IE @mojodna @bdon

**Comment by mojodna** [comment]
@bdon which version of IE? IE 11 on Windows 8.1 is ✅ 

Some spot checks uncovered problems with the icons on the Export Form (now fixed, soon to be deployed).

**Comment by bdon** [comment]
@mataharimhairi do you remember what one of the users reported as being broken on IE? I believe it was the landing page?

**Comment by mataharimhairi** [comment]
correct. it was the landing page that wasn't working on IE.

**Comment by mojodna** [comment]
IE 10 is the problem, FWIW.

**Comment by mojodna** [comment]
Fixes deployed to staging (along with everything else).
