### ISSUE TITLE
Select Features tab - Hazards has a + but nothing expands when clicked

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#23]
HDM -> Hazards

**Comment by bjohare** [comment]
The feature tress are generated from the HDM Data Model at https://github.com/hotosm/presets/blob/master/HDM.xml. This file is missing the type attribute on the Hazzard Item which means it doesn't get added as an item in the Hazzards on the export tool's feature tree. Also, the HDM Model referenced above, is missing some road features, eg motorway... which means motorways won't be exported for users choosing the HDM. Someone needs to review this model for completeness.

**Comment by bjohare** [comment]
Added hazard items.

**Comment by mataharimhairi** [comment]
The hazard feature tags are now present in the HDM Data Model tree. I went through all of the branches down to their lowest levels and all the branches that have a + symbol contain feature tags.

When the last branch (Landuse) at the tree bottom of the tree is expanded, the page doesn't automatically scroll down to display the feature tags. Would it be possible to enable this, so it displays them as it currently looks as though it is empty.
