### ISSUE TITLE
Not assume that all exports are for activations?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-export-tool2#234]
The hint text in the `Project` box says `Which activation is this export for`. Maybe we can just add `e.g.` in front, or make it more generic?

**Comment by bdon** [comment]
maybe we can just add (optional) to the text? or change to "Which project or activation this export relates to" ? 

Blank is already an accepted value

**Comment by cgiovando** [comment]
👍 on `"Which project or activation this export relates to"` - what do you think @mataharimhairi

**Comment by mataharimhairi** [comment]
I think "Which project of activation this export relates to" is good!
