### ISSUE TITLE
Email Addresses of V2. Users with Presets

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#235]
@bdon could you please retrieve the email addresses for users of V2. that have presets, so we can contact them about migrating over to the V3. and the use of YAML. I'll get in touch once we have the emails and a screencast showing how to convert the configurations #227 - Thanks!

**Comment by bdon** [comment]
query to get emails of users who uploaded presets:
 
    select distinct email from tags, jobs, auth_user where data_model = ‘PRESET’ and tags.job_id = jobs.id and jobs.user_id = auth_user.id;
