### ISSUE TITLE
Need indication of why "Create Export" is grayed out

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#24]
I did a clone export and then changed the selection of items to export. went to the last page and I could click create export, but then an error dialog window popped up that said "Invalid form", from then on the "Create Export" button has been greyed out (lighter shade and the no icon when hover over) but there is no indication what is wrong with my export job.

**Comment by bgirardot** [comment]
I changed a few things with no luck.
turns out I seemingly had to change the selection area ?
What if i wanted the exact same area with but with different things exported?
So I am not sure what the point of the Clone Export button is and if it can't be the exact same area why not and if not, the greyed out button still should say why it is unavailable, and the clone export, should not clone the export area

**Comment by mataharimhairi** [comment]
@bgirardot a fix has been referenced to this issue. could you please review and see if it has been addressed. if so please go ahead and close the issue. cheers!

**Comment by bgirardot** [comment]
No, I don't see this as being fixed yet. It is possible some of the submissions made it more difficult to get to the last screen without things being properly filled out, but you can still end up there and have a grey'ed out "create export" button with no indication why. You can see this in the attached screenshot, and honestly, I think it might have been harder to get to that spot, but I have no idea why it is greyed out so I can't tell you how to reproduce it. I will try and get steps to reproduce it.
![2015-10-05_14h19_32](https://cloud.githubusercontent.com/assets/265831/10280319/9df5d9d8-6b6c-11e5-8ff1-8e8ee78c49e4.png)

**Comment by mataharimhairi** [comment]
I tried replicating the issue, by cloning existing exports but changing the selected features. The 'Create Export' button is not being greyed out. 

@bgirardot Could you please try to replicate the issue and note the steps, so that Brian and I can take a look at it and find an appropriate solution. 

@bjohare At the very least we could provide an error message as to what is happening. Along with the necessary steps to rectify the problem.

**Comment by mataharimhairi** [comment]
https://github.com/hotosm/osm-export-tool2/issues/56
