### ISSUE TITLE
Link to create new export after one is completed?

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-export-tool2#241]
After an export has finished, there's no explicit suggestion for the user on what to do other than cloning or rerunning the export, or downloading the data. Might be good to have a "link out" for the user to create new exports?

**Comment by mataharimhairi** [comment]
I think that might overcomplicate things a bit. In terms of presenting too many options to the user. It is easy enough for the user to click the 'Create' page link for them to be redirected to create another export.

**Comment by bdon** [comment]
Yep, this is consistent with the export tool v2 as well
