### ISSUE TITLE
No Option to Delete Export

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#242]
I just realised there is no option to delete exports when I was generating jobs for hurricane irma, and did a couple of incorrect ones. 

I've linked the right ones through the OSM wiki page for the activation , but my concern is that users going directly to the Export Tool to look for hurricane irma exports might select incorrect ones instead of the proper ones.

The user should have the ability to delete job created by themselves through the UI.

**Comment by bdon** [comment]
Is this functionality already covered by making an export "Published" vs private?

**Comment by mataharimhairi** [comment]
I don't believe so. Whether it is public or private, the owner should still have the ability to delete the export. V2 allows users to delete their exports, so the functionality was there, maybe it was just disabled while work was carried out on OSM2HDX.

<img width="1180" alt="screen shot 2017-09-07 at 12 20 10" src="https://user-images.githubusercontent.com/8972913/30181144-25e48a40-93c7-11e7-9ada-894667edbb15.png">
