### ISSUE TITLE
Add Preset to YAML in Learn Section

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#245]
There is no documentation in the YAML section on the Learn page about converting Presets to YAML

**Comment by bdon** [comment]
Is there anything specific to previous Preset users that needs to be covered? I imagine those that authored Presets for v2 would use the docs to understand the new YAML format.

**Comment by bdon** [comment]
added short description to http://localhost:8000/en/v3/learn/yaml
