### ISSUE TITLE
System Admin Launch Plan

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#250]
@mojodna @bdon @cgiovando 

HOT will be conducting a Tech Sprint next week 18th - 22nd October, which aligns nicely with the launch of the V3. to provide the time and attention if needed.

We should also specifically block out time for @david-hotosm on Monday to be present for the launch. Could you please also do up a quick doc of launch requirements to share with everyone (ie. url name change and when to deactivate V2).

**Comment by bdon** [comment]
* change DNS for export.hotosm.org to point at exports-prod.hotosm.org
* add new DNS record (exports-v2.hotosm.org?) to point at existing export.hotosm.org

Is that all? I don't see any harm in leaving the old version running, maybe we add a link to it on the homepage?

**Comment by mojodna** [comment]
* update https://github.com/hotosm/osm-export-tool2/blob/master/ops/systemd/docker.nginx-ssl.service on prod to match the new hostname
* replace existing SSL cert
