### ISSUE TITLE
Clone Export does not clone the Selected Features

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#26]
I have an export (http://hot.geoweb.io/en/jobs/ae5e5522-debd-4c05-ba8c-611ccad52233/) that just has a few features selected.

When I clone it, and go to the features, the default of all HDM features are selected.

Not sure what the actual expected Clone behavior is, but the the word clone suggests exact duplicate so I would think that would mean the features selected would be exactly the same as well.

**Comment by bjohare** [comment]
Seems to be fixed now..

**Comment by mataharimhairi** [comment]
@bgirardot a fix has been referenced to this issue. could you please review and see if it has been addressed. if so please go ahead and close the issue. cheers!

**Comment by mataharimhairi** [comment]
I tried to replicate the issue by cloning the following export: http://export.hotosm.org/en/exports/53c4a6bf-5c4b-4a56-8fa1-977d42894b4f/

Looks like the same features originally chosen are automatically selected for the clone. I tried this multiple times, selecting various 'Publish Publicly' and 'Save Privately' options for the features.
