### ISSUE TITLE
Provide a name input field for saving tree tag selection locally (privately) or globally (publicly)

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#30]
Right now if I do a set collection of features to export and then save them either locally or globally, they are all named Custom HDM Preset, even ones based on the OSM Data Model are called Custom HDM Preset

When selecting to save them locally or globally, there should be an input field to give them a name so they are not all named the same thing.

**Comment by bjohare** [comment]
Rather than adding another input field to the create export form, I've updated the Preset task to use the Export Name as the name for the preset and the filename is now set to 'job_name_preset.xml'

**Comment by bgirardot** [comment]
I'll leave this up to you as this is for sure an improvement, but I think naming it might be better from a resuse stand point.

That way I can name the selections as what they are (hospitals_heliports for example) instead of the name of the job, boma_south_sudan_presents, which doesn't help others or myself know what the preset file will include.

**Comment by bjohare** [comment]
Going to leave this for now. Have marked it as feature request for future development.

**Comment by bdon** [comment]
New feature selection form has name and description fields.
![screen shot 2017-06-26 at 8 21 19 am](https://user-images.githubusercontent.com/77501/27538969-877ee7b8-5a48-11e7-951e-0b1b26fa9a51.png)
