### ISSUE TITLE
Global store and Local Store might just be more clearly called Public and Private

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#31]
if possible, I think changing "Global Store" and "Local Store" to much simpler and clearer "public" and 'private' (or "personal) would help usability.

Local store is not even the typical usage of "local" which usually means stored on your local machine, meaning your desktop or laptop.

The tool tip has good language "your personal store" although I would use the full word "storage" again, to be more clear, especially for translations or non-native English speakers who need to read the English version.

**Comment by bjohare** [comment]
Not sure where you've seen Global Store / Local Store. Have updated the tooltips.

**Comment by bgirardot** [comment]
Create Job -> Export Summary

X Save feature selection locally
X Publish feature selection globally
X Publish export globally

And the tool tips for them.

I would make them:

Save feature selection to personal options (or storage, options, etc)
Publish feature selection publicly
Publish export publicly

"Globally" is just not clear and has a lot of meanings, but what we are really talking about is just making the things public, instead of keeping them private.

**Comment by bjohare** [comment]
Updated these labels.

**Comment by mataharimhairi** [comment]
Confirming that the text on the 'Export Summary' tab during the create process has been updated to use 'Public' in place of 'Globally' and 'Private' in place of 'Locally'.

<img width="603" alt="public_private" src="https://cloud.githubusercontent.com/assets/8972913/10014097/867a27c8-6149-11e5-85e9-f3044e3b8c27.png">
