### ISSUE TITLE
Minor: UI: New user onboarding.

### ISSUE THREAD

**Issue by jdtoy** [hotosm/osm-export-tool2#32]
> **Fresh Humanitarian Maps**
>
> Download up-to-date humanitarian maps for GIS analysis or for use in GPS devices.
> 
> This platform allows...

This feels almost petty, but the About section on the front page could be tweaked to help onboard new users who are also new to HOT/OSM. The heading and sentence above is my attempt at a succinct user-focused description of what this tool does.

**Comment by bjohare** [comment]
Thanks. Have updated the about info.

**Comment by mataharimhairi** [comment]
Will be doing a final revision of the about and help documentation this week before the live release on Monday the 28th September.
