### ISSUE TITLE
Question: I don't see the "create" button for jobs

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#33]
I think I must have seen this button or link at one time, but I haven't seen it for a while, I did almost all my testing by having to "clone" an existing export job.

What am I not understanding or not doing right that I don't see how to "create" export jobs?

Help seems to indicate it would just be on the menu bar to the left of "Exports" but I don't see it.

sorry for the basic question.

**Comment by bgirardot** [comment]
Actually, I thought I imagined it, but click on the "OSM Export Tool" link in the menu bar takes me to "Create", but I thought there was supposed to be a "Create" button next to "Exports"

**Comment by bjohare** [comment]
Hi Blake, I think the idea is to have as few buttons and links as possible.. but I agree that the lack of a 'Create' button is confusing.

**Comment by bgirardot** [comment]
Ya, I agree, a Create button is needed. Otherwise it is too random seeming which leads to confusion.

**Comment by bjohare** [comment]
Added 'Create Export' link.

**Comment by bgirardot** [comment]
Looks great, thank you very much.
