### ISSUE TITLE
Need an "About" page

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#34]
We need to add an "About" page like we have for the Tasking Manager, lists and thanks the sponsor of the tool and credits Brian however he feels is most appropriate.

The TM also pulls in info from github (I think) to display the exact release which is kind of nice

http://tasks.hotosm.org/about

Maybe just a stub for now to get it on the UI somewhere

**Comment by bjohare** [comment]
Have added about page. Will look at git version info as lesser priority.

**Comment by bgirardot** [comment]
Looks good. I'll leave this issue up to you to close or leave open to remind us about further filling out the page.

**Comment by mataharimhairi** [comment]
Will be doing a final revision of the about and help documentation this week before the live release on Monday the 28th September.
