### ISSUE TITLE
Overlapping areas in Export List map view, can't select "bottom" area

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#35]
I see along W. Africa on the alpha site two areas that overlap. I can click select the larger one, but have no way to to click select the bottom one, or roll over it to see it get highlighted in the list of exports.

Maybe one way to deal with it is a 'toggle' in the exports list to turn off the map drawing of the one that "covers" the smaller one? Just an idea. 

Or edges only are clickable so you can click on things "under" others ? Not sure I like that one, but it is not the end of the world either.

This will probably come up in actual usage too as people do larger exports of an administrative district and then other people do smaller exports of just part of a city for mapping or something.

**Comment by bjohare** [comment]
hmm.. you're probably right about that. Will try the hide option.. Don't like the clickable edges as that makes the double click to redirect to the export detail page more difficult for the user.

**Comment by bjohare** [comment]
Added ability to hide features.. seems to do the trick.

**Comment by mataharimhairi** [comment]
I couldn't find the Exports Blake was referring to in West Africa, but created a similar set up with exports of Nairobi, Kenya.

I didn't find any hiding capability, but was able to select the smaller export extent covered by the larger export area simply by clicking on its edges. Is this the end solution?

**Comment by bjohare** [comment]
In the list of exports, on the right there's a 'eye' icon. Clicking on this toggles the visibility of the corresponding feature on the map.. maybe not clear?

**Comment by bgirardot** [comment]
This item, like many of the items Mhairi closed was addressed and solved for me and I should have marked it closed myself. I think it can be marked closed.

**Comment by mataharimhairi** [comment]
Sorry if this has caused any confusion @bgirardot . I thought I would help address some of the issues by testing and verifying that they had been successfully solved. 

And thanks for clearing up my confusion @bjohare. Unfortunately I don't think the 'eye' icon's capabilities are very clear unless they read the help documentation. Would we be able to offer a pop-up info box when users hover over it?

**Comment by bgirardot** [comment]
@mataharimhairi I apologize for the confusion, I should have reviewed my own issues and given feedback, sorry got sidetracked on other things. Thank you for cleaning up my list of open issues that should have been closed.

As do the "eye" icon, I think that is generally getting more understood to indicate "show/do not show" but as I recall the icon itself was a little "muddy" at the size used (sorry can't look at the moment)

I think it is the same eye icon used in the josm editor to turn on and off layers, so the consistency there is helpful as well (totally not able to tell what the icon is in josm, but that is another matter ;)
