### ISSUE TITLE
BBox modifiy hander missing when job selected from Nominatim

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#36]
Bounding box handler is missing when the export bounding box is selected from Nominatim and it's greater than the maximum extent allowed.

**Comment by bjohare** [comment]
Fixed.

**Comment by mataharimhairi** [comment]
Replicated this by searching for Algeria, Sudan and South Africa, and the bounding box handler successfully appeared each time.

<img width="616" alt="sudan" src="https://cloud.githubusercontent.com/assets/8972913/10014966/adc9916e-614f-11e5-8ff0-e04bd0ffe088.png">
