### ISSUE TITLE
Can't create new jobs for some reason

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#37]
I seem to get through the process ok, but then when I do finally click "Create Export" it just forever sits with the spinning gear icon.

Anyone else have that problem or just me?

**Comment by bjohare** [comment]
Could be that you need to login again? Just tried it and it looks fine to me..

**Comment by bjohare** [comment]
Will add error handler there if user not logged in..

**Comment by bjohare** [comment]
Ok, this is caused by validation check on server for 'event' field. Fixed now.

**Comment by bgirardot** [comment]
works now, thank you very much.
