### ISSUE TITLE
'Select Export Area' button resets the map

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#38]
Selecting the 'Select Export Area' button resets the map to the default scale, which is duplicating the functionality of the 'Reset Button'. Could this be changed so that the 'Select Export Area' button simply clears the bounding box, but stays at the same scale and location so that the user can create a new bounding box?

**Comment by bjohare** [comment]
Think this is a duplicate of #17. Maybe try to refresh the page using Ctrl/Shift F5 to see if this is fixed.

**Comment by mataharimhairi** [comment]
Yes. It's working! Cheers Brian.
