### ISSUE TITLE
Add groups of users with different export extents

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#39]
Need ability to add users to a group which determines how large their export extent can be.

**Comment by mataharimhairi** [comment]
As discussed in the meeting, if the admin site is documented well than we can create these groups as and when they are required, during activations for example.

**Comment by mataharimhairi** [comment]
Export Extent Groups: 
- Default 2,500,000 sq km
- Medium 5,000,000 sq km
