### ISSUE TITLE
Login with OSM Username

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#4]
Investigate the ability for users to login with their OSM username. Currently the tool is set for users to register with an email address as this allows a link with their completed exports to be emailed to them. 

[Python Social Auth](https://github.com/omab/python-social-auth) is a social registration mechanism with its base code from django-social-auth. It implements a common interface to define new authentication providers from third parties.

**Comment by mataharimhairi** [comment]
@bjohare If time permits, can you investigate this functionality.

**Comment by arushivashist** [comment]
I did a little investigation on the issue: https://github.com/hotosm/osm-export-tool2/issues/4

The ability for users to login to the new Export Tool using their OSM username as opposed to signing up with their email address will be consistent with other OSM websites like the Tasking Manager.

Tasking Manager is developed in Python using the Pyramid framework. So the section where it defines all the auth tokens might be little different, but worth looking at:
https://github.com/hotosm/osm-tasking-manager2/blob/master/osmtm/views/osmauth.py

I found short tutorials where they have explained from how the settings file has to changed, all the way to acquiring the keys:
[1] http://artandlogic.com/2014/04/tutorial-adding-facebooktwittergoogle-authentication-to-a-django-application/
[2] http://chriscauley.github.io/2014/07/25/python-social-auth-tutorial/

I hope that this functionality can be implemented, if we have time in our hands.

**Comment by mataharimhairi** [comment]
Varying area extent selection permissions also need to be assigned to the different types of users such as project manager, etc.

**Comment by mataharimhairi** [comment]
Users can now register and login with their OSM username. An email address will be requested when they first sign up so that an email can be sent to their account to notify them when their export is ready, along with a link to their downloads.
