### ISSUE TITLE
Can't upload a preset file

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool2#40]
The button on both the jobs and presets page (http://hot.geoweb.io/en/jobs/configurations/) doesn't seem to do anything (at least on Firefox). Don't see an error in browser console. Not sure if it's supposed to work yet, but anyway..

Also, is the beta running on an old data set? Tried an export for Dar es Salaam, but it looked quite out of date.

**Comment by bjohare** [comment]
Thanks Paul, see the button issue and will fix. Looks like a firefox issue.  Looking at the minutely update logs it seems they are being applied but will investigate further. What were you expecting to see in Dar es Salaam?

**Comment by PaulUithol** [comment]
A lot more buildings.. basically, the export from http://hot.geoweb.io/ looks like it would have looked at the end of June/start of July.

From http://export.hotosm.org/:

![dar_current-export](https://cloud.githubusercontent.com/assets/670670/9957754/2455852c-5e03-11e5-9880-15f144bae292.jpg)

From http://hot.geoweb.io/:

![dar_export-tool2](https://cloud.githubusercontent.com/assets/670670/9957755/2457af1e-5e03-11e5-8bde-f54ddec7b5ab.jpg)

**Comment by bjohare** [comment]
Paul, thanks for this. Looks like there is an issue with the application of minutely diffs on the dev instance of overpass. Changesets are being fetched correctly but are not being applied. Data is current as at Thu Jun 25 19:50:03 UTC 2015. Will aim to fix this between beta and live release when deploying to live server.

**Comment by PaulUithol** [comment]
It is correct that the data exported at this moment is still stuck in June? Since it still seems to be, in an export just moments ago.

**Comment by bjohare** [comment]
Will be fixed for live release which should be happening in the next 24hours.
