### ISSUE TITLE
Add maps.me mwm export

### ISSUE THREAD

**Issue by Zverik** [hotosm/osm-export-tool2#42]
[Maps.me](http://maps.me) application uses its own data format, mwm + mwm.routing. There is a binary + a script to produce these out of pbf/o5m/bz2 source files. It would be great to add mwm exporting to the tool. [Ilya Zverev](http://ilya.zverev.info) can help with the integration.

**Comment by harry-wood** [comment]
+1 Could be a nice addition.  I was reminded of this by an article today about MAPS.ME use in humanitarian aid: http://thenextweb.com/dd/2015/09/30/openstreetmap-just-got-a-big-boost-thanks-to-maps-me

**Comment by bgirardot** [comment]
I agree, I really look forward to being able to offer our data via maps.me as well. The more options we can offer the easier it will be for the communities and organizations we work to use our data.

**Comment by Zverik** [comment]
Do I understand correctly that if an export task produces two files, they must be somehow archived?

**Comment by pnorman** [comment]
> There is a binary + a script to produce these out of pbf/o5m/bz2 source files

Could you provide a link?

**Comment by mataharimhairi** [comment]
@Zverik could you please provide the link to the binary + script you mention above. HOT is looking at potentially having an intern through the Outreachy program work on this, as well as the inclusion of translation files as an admin feature. It would be great to be able to investigate the scope to see if it is within their capacity and who might be able to mentor them.

**Comment by Zverik** [comment]
Hi, I've compiled the latest generator tool: http://tile.osmz.ru/mapsme-generator-151005.tgz

**Comment by pnorman** [comment]
> Hi, I've compiled the latest generator tool: http://tile.osmz.ru/mapsme-generator-151005.tgz

Is this source not available?

**Comment by Zverik** [comment]
It is. I just followed [INSTALL.md](https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#ubuntu-1404). You asked for binaries — I made binaries :)

**Comment by unithiyashree** [comment]
Hey, I ran this with a pbf created from HOT Export tool, but I am getting an error.

LOG TID(1) INFO    9.207e-06 generator_tool/generator_tool.cpp:119 main() Generating intermediate data ....
LOG TID(1) INFO  0.000106423 Reading OSM data from /tmp/tmp.lmFHj58jYU/ffdbo.o5m
LOG TID(1) INFO  0.000118266 generator/osm_source.cpp:532 GenerateIntermediateDataImpl() Data source: /tmp/tmp.lmFHj58jYU/ffdbo.o5m
LOG TID(1) INFO    0.0477504 generator/osm_source.cpp:545 GenerateIntermediateDataImpl() Added points count =  186820
LOG TID(1) INFO   1.8739e-05 generator_tool/generator_tool.cpp:139 main() Generating final data ...
LOG TID(1) INFO   9.2771e-05 generator/intermediate_data.hpp:383 InitStorage() Nodes reading is started
LOG TID(1) INFO    0.0224767 generator/intermediate_data.hpp:398 InitStorage() Nodes reading is finished
LOG TID(1) INFO    0.0225714 Offsets reading is started for file  /tmp/tmp.lmFHj58jYU/ways.dat.offs
LOG TID(1) INFO    0.0226774 Offsets reading is finished
LOG TID(1) INFO    0.0226848 Offsets reading is started for file  /tmp/tmp.lmFHj58jYU/relations.dat.offs
LOG TID(1) INFO    0.0227044 Offsets reading is finished
LOG TID(1) INFO    0.0227094 Offsets reading is started for file  /tmp/tmp.lmFHj58jYU/ways.dat.id2rel
LOG TID(1) INFO    0.0227944 Offsets reading is finished
LOG TID(1) INFO    0.0228738 generator/polygonizer.hpp:58 Polygonizer() Polygonizer thread pool threads: 8
LOG TID(1) INFO    0.0238034 Reading OSM data from /tmp/tmp.lmFHj58jYU/ffdbo.o5m
./bin/generator_tool: symbol lookup error: ./bin/generator_tool: undefined symbol: _ZN7QString13toUtf8_helperERKS_

**Comment by pnorman** [comment]
> @Zverik Hey, I ran this with a pbf created from HOT Export tool, but I am getting an error.
> [...]
> LOG TID(1) INFO 0.0238034 Reading OSM data from /tmp/tmp.lmFHj58jYU/ffdbo.o5m
> ./bin/generator_tool: symbol lookup error: ./bin/generator_tool: undefined symbol: ZN7QString13toUtf8_helperERKS

This looks like a fairly standard library path error

Did you install Qt 5.5? https://github.com/mapsme/omim/blob/master/docs/INSTALL.md#ubuntu-1404 has package lists. Some are probably only needed for building as opposed to run time, but it's easiest to just get them all.

Alternately, did you build the binary yourself? It's probably a good idea to do so, since you'll probably want to do that eventually for deployment, instead of relying on a binary blob.

**Comment by Zverik** [comment]
Yes, you need Qt 5.3 or higher to run `generator_tool`, and a number of packages listed on `INSTALL.md` page to run OSRM tools for routing indices.

**Comment by unithiyashree** [comment]
No, I didn't build them , I have downloaded it from the previous comment. Yes, I have installed and then it worked. So , now I am adding this format to the export tool. :)

**Comment by bdon** [comment]
@Zverik can you provide a compiled PBF to MWM generator for us? The link Hi, I've compiled the latest generator tool: http://tile.osmz.ru/mapsme-generator-151005.tgz has expired. We're using Ubuntu 14.04, so let us know what libraries we should install through `apt` to use the binary.

**Comment by Zverik** [comment]
Do you plan to move to Ubuntu 16.04, by any chance? :)
(I'll try building the generator in a few days)

**Comment by bdon** [comment]
@Zverik I was mistaken, we're using Ubuntu 16.04 already

**Comment by mojodna** [comment]
We weren't when I first tested this, so this should get easier now. I'll give it another go next week.

**Comment by bdon** [comment]
@Zverik any updates on this?
