### ISSUE TITLE
Export configs (presets) could do with a description field

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#47]
Configuration files could do with a description field to make them more reusable.

**Comment by unithiyashree** [comment]
can someone please elaborate on this??

**Comment by mataharimhairi** [comment]
@unithiyashree I believe Brian is suggesting that an additional column be added to the table in the 'Presets' page to describe what the associated preset (config file) contains. As in what features it will export for download.

**Comment by bdon** [comment]
New feature selection form has both name and description fields:

![screen shot 2017-06-26 at 8 21 19 am](https://user-images.githubusercontent.com/77501/27538994-9e706e9c-5a48-11e7-98c1-b826c5cea0d6.png)
