### ISSUE TITLE
Set up code for easy incorporation of .po translations to frontend

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#49]
The transform and translate configuration file functionality was made redundant after a user survey was conducted on the Export Tool. The results showed that these are only used by a handful, and the processing stress put on the tool outweighed its benefits.

The thought was that those individuals that are tech savvy enough to create the configuration files could run the process outside of the tool, and we would focus on enhancing the exporting tag features for the majority of the users, making it easier to select features and provide more format choices. 

However there has been opinions voiced that they would like to see the translate functionality kept in the new tool, and we are working to make it possible to add this in as an admin feature. So that they will be able to add tried and tested translate files to the tool, that can then be selected from a dropdown box by all the users.

Unfortunately we had to draw the line at some point to ensure that we deliver a strong end product, and can not add this functionality during the redevelopment. The new code will have support documentation as well as in-line documentation so that it will be much easier for enhancements and future adaptations, as we are already getting requests to include more export formats #42.

**Comment by mataharimhairi** [comment]
@bjohare I know that you have been working on this, incorporating Transifex to do the translations. Last thing I heard you had it more or less running, just not hooked up to the API. Any update?

**Comment by bdon** [comment]
The refactoring of the UI means that all the localization previously done on the backend now needs to be re-implemented in the new React-based frontend. We should use react-intl and hook this up to .po files so we can use Transifex.

**Comment by mojodna** [comment]
`react-intl` is now wired up; there are some straggler strings in `ui/app/components/aoi`. The corresponding Babel plugin is also configured, exporting strings to `ui/build/messages/` as JSON (what FormatJS uses).

Transifex supports JSON, but existing translations can only be downloaded in the format that they were created in, so both existing Transifex components can only be downloaded in gettext format (PO). A response from Transifex support said that "Translation Memory" can be used to automatically translate strings between components, automatically populating the JSON versions that have yet to be uploaded.

@mataharimhairi has been trying to reach @bjohare and @dodobas to gain admin access within HOT's Transifex organization, so getting that will set off the next flurry of activity when it comes to tweaking strings, straightening up IDs, and getting content translated.

**Comment by mojodna** [comment]
@bgirardot granted project admin access, so we're clear there.
