### ISSUE TITLE
Provide Static Styling Files for Download

### ISSUE THREAD

**Issue by mataharimhairi** [hotosm/osm-export-tool2#5]
Provide users with static styling files for specific file formats when selected for export. For example, an OSM style layer file will be downloaded by default along with the users area of interest when an ESRI shapefile is selected for export.

https://github.com/hotosm/HDM-CartoCSS

https://github.com/gravitystorm/openstreetmap-carto

**Comment by mataharimhairi** [comment]
It appears that ESRI have created a toolset that applies OSM styling, therefore making it redundant to provide static styling files for ArcMap : 
http://www.esri.com/software/arcgis/extensions/openstreetmap
http://www.arcgis.com/home/item.html?id=75716d933f1c40a784243198e0dc11a1

Instead the focus will be providing static styling files for QGIS, as currently none of the plugins in version 2.8 provide this ability:
http://www.ewan.cc/?q=node/129 
https://github.com/charleyglynn/OSM-Shapefile-QGIS-stylesheets

**Comment by arushivashist** [comment]
I have been doing a little investigation on #5
After downloading shapefiles [1] and loading them on qgis, I began collecting all the possible qml files [2] [3] from the links as given the document [4]. 

After experimenting with loading various styles, I am afraid was the picture was not exactly the osm style result [5] that we were expecting [6]. As I learned more, I came to know the existing repositories used for qml files are owned by users design their own style files for achieving effects that they like/require. So, maybe the irregularity lies in the qml files. 

More information in [4].

[1] http://wiki.openstreetmap.org/wiki/Shapefiles#Download_shapefiles
[2] https://github.com/charleyglynn/OSM-Shapefile-QGIS-stylesheets
[3] http://www.ewan.cc/?q=node/129
[4] https://docs.google.com/document/d/1AJvPYMHMW4LqCpUMdQEFfvq7zYpp2Wr9GQjdAHd4_Lk/edit?usp=sharing
[5] http://www.openstreetmap.org/#map=8/-6.681/107.875
[6] 
![screenshot from 2015-08-24 09 14 06](https://cloud.githubusercontent.com/assets/7515388/9439373/eec60da6-4a83-11e5-8a36-afd471b9a5fa.png)
