### ISSUE TITLE
What does Building digitizing mean?

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#54]
An explanation would be good

**Comment by mataharimhairi** [comment]
Could you please elaborate more on this issue Severin. Where are you reading this 'Building digitizing'?

**Comment by bjohare** [comment]
This is on the HDM Feature Tree and comes from the HDM Data Model. We can rename this if necessary.

**Comment by mataharimhairi** [comment]
Linking this to the other two issues requesting that the HDM Data Model be reviewed by the Activation WG:

hotosm/osm-export-tool2: Issue #84
hotosm/osm-export-tool2: Issue #79
