### ISSUE TITLE
Personal preset or default schemes

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#55]
When using a preset and not the 2 default schemes, the user has nevertheless to choose one of the default schemes. An explicit skip button would bee good

**Comment by bjohare** [comment]
Not sure what you mean. There is a next button on the Tag selection tab.. should be renamed to 'Skip'?

**Comment by severinmenard** [comment]
sorry, tried to mean that if the user wants to use a present and not the OSM or HDM schemes, the tree tag step is unnecessary and the user should be informed he can skip it

**Comment by mataharimhairi** [comment]
@severinmenard there is a button at the bottom of the page which was named 'Next'. brian has now changed this to 'Skip', to help clarify this option to the users.
