### ISSUE TITLE
Name of shp from generic scheme

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#57]
Would be good to add “planet” into the name of the generic shp, to differentiate better with the thematic one (that includes thematic in its name)

**Comment by mataharimhairi** [comment]
@severinmenard we wanted to go for something that everyone would understand, as not all the users of the export tool will necessarily know what is a planet file, but knows OSM. at this point in time we feel that the naming convention chosen is sufficient.
