### ISSUE TITLE
Add info regarding the date of the OSM

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#62]
Currently seems there is no information about how old is the OSM data we get from the service. A clear mention of the last update is required

**Comment by mataharimhairi** [comment]
This will be added to the 'About' and 'Help' page in the live release.

**Comment by bjohare** [comment]
The data is updated minutely.

**Comment by severinmenard** [comment]
Great for the minute update, so it is worth to mention it from the start page in bold

**Comment by mataharimhairi** [comment]
This has been added to the site's help documentation http://hot.geoweb.io/en/help
