### ISSUE TITLE
The search place bar is not large enough to display the full description text

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#65]
will be worse with Latin languages

**Comment by bjohare** [comment]
Increased width of search box. Looks reasonable now.

**Comment by severinmenard** [comment]
still a bit too short in 1366x768 (see below)
![selection_014](https://cloud.githubusercontent.com/assets/1291055/10291812/53ef1c12-6b9b-11e5-86d0-4089eef6ffe1.png)

**Comment by mataharimhairi** [comment]
@severinmenard @bjohare Should we change the text instead of the box length? Perhaps 'Search place or xmin,ymin,xmax,ymin'? This should give us a little more leeway.

**Comment by severinmenard** [comment]
Typically French produces longer text chains than English and I do not see
well how to rephrase shortly

**Comment by bdon** [comment]
It's wide enough to fit the German text now.
