### ISSUE TITLE
UI Help Documentation

### ISSUE THREAD

**Issue by arushivashist** [hotosm/osm-export-tool2#7]
Export Tool requires a Help section that gives the user a gist of how to use the tool. 
For now, the Help documentation has been divided into three sections: Create new, Export and Store.
Here is the link to the document: 
https://docs.google.com/document/d/1xcxZxNt9ofl3vXA6rKso2_braSQMWwVrzO8XVXNwbng/edit?usp=sharing

**Comment by mataharimhairi** [comment]
https://docs.google.com/document/d/1AxIW0okCjuOZhn8GFmGNM5l3fYIOsiKk7e9aXkxYydQ/edit?usp=sharing

**Comment by bjohare** [comment]
Help documentation added.
