### ISSUE TITLE
Uploading preset file fails w/ "Uploaded config file has invalid content: text/plain"

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool2#71]
On Chrome, I can upload a preset file (not on Firefox; see #40. However, it doesn't complete, giving the following error message:

```
There was a problem with your configuration upload.
Uploaded config file has invalid content: text/plain
```

As far as I know, an XML file should be plain text? The file validates fine in a validator (it's derived from the HOT HDM file on the old export tool, adding boundaries), and works in the old export tool. I've attached the file in question, did have to rename it to .txt for it to upload to github.

(Also, it's confusing me that I'm required to give a filename before uploading; can't it use the filename as used on the fs by default?)

[HOT_HDM_with-boundary.txt](https://github.com/hotosm/osm-export-tool2/files/5382/HOT_HDM_with-boundary.txt)

**Comment by bjohare** [comment]
Does the file have the xml declaration?

**Comment by PaulUithol** [comment]
Hmm, good one. Looks like it doesn't. Didn't trip over the old tool though, it's the default file there. Let me try that.

**Comment by bjohare** [comment]
The filename field is intended as a more descriptive name.. should probably be renamed to description?

**Comment by PaulUithol** [comment]
Well, that seems to work, thanks! Yeah, that would be clearer; should it be required though? Or maybe only if published globally?

**Comment by bjohare** [comment]
possibly, although just trying to avoid the tool getting cluttered with 'stuff' rather than actual correct files.. might be a bit restrictive though?

**Comment by PaulUithol** [comment]
Well, with the way it's now, you're probably going to end up with a whole lot of 'asdf' files. Where the actual filename would be more useful..

**Comment by bjohare** [comment]
we hold the filename as well, but yes I take your point.. something to consider for the next iteration?

**Comment by PaulUithol** [comment]
Yeah, probably. Closing this one though.
