### ISSUE TITLE
Export contains way less tags than expected based on preset file

### ISSUE THREAD

**Issue by PaulUithol** [hotosm/osm-export-tool2#74]
Could you explain how/what information gets parsed from preset files exactly? When using the 'default' preset file from the old hot export tool (HDM), a lot of information seems to be missing in the export (the old tool did have a "add default tags" option; but a key like `highway` is also in the preset).

Testing with the preset we've been using (see attachment), the `planet_osm_line` shapefiles only contains columns for `osm_id`, `waterway` and `z_index`. While I expected it to contain `highway`, `layer`, `covered`, `smoothness`, `width`, `oneway`, `bridge`, and so on.

Alternatively, is there perhaps a way in the new tool to easily list the tags that you'd want added to the selected ones?

[RamaniHuria.txt](https://github.com/hotosm/osm-export-tool2/files/6693/RamaniHuria.txt)

**Comment by bjohare** [comment]
The preset parser looks for <item> elements that have a 'type' attribute (node, way etc..). It then looks for child 'key' elements of the <item> as these are the elements describing the key:value pairs for that item. In the example preset you supplied there is a <item name="Road" type="way"/> but the item does not have a child 'key' element and is therefore skipped. The same applies to the missing 'smoothness' attribute as it doesn't appear as a 'key'. 

I've fixed an issue where only the first child 'key' element is picked up. It should now pick up multiple 'keys' elements of <item>

**Comment by PaulUithol** [comment]
Is there a reason it doesn't parse `combo` or `check` elements? The current
parser does, and I would probably consider this expected behavior? Those
make up a the majority of most preset files.

The preset parser looks for elements that have a 'type' attribute (node,
way etc..). It then looks for child 'key' elements of the as these are the
elements describing the key:value pairs for that item. In the example
preset you supplied there is a but the item does not have a child 'key'
element and is therefore skipped. The same applies to the missing
'smoothness' attribute as it doesn't appear as a 'key'.

I've fixed an issue where only the first child 'key' element is picked up.
It should now pick up multiple 'keys' elements of

—
Reply to this email directly or view it on GitHub
<https://github.com/hotosm/osm-export-tool2/issues/74#issuecomment-145044932>
.

**Comment by bjohare** [comment]
the new tool allows for finer grained exports in that we also take the 'values' for the keys so for example instead of just pulling out all 'highway' tags you can specify a highway with a specific value eg highway:motorway.. If we parse the 'combo' element then what do we take as the value.. since that's intended as a multiple choice for the user? It would be incorrect to take all the values as that's not what the user intends?

**Comment by bgirardot** [comment]
I think the combo item would use the value list as OR's for selection purposes. They would be intending to find key=value pairs that were created with the preset in theory, so in theory we would want to find all objects with those possible key=value pairs.

**Comment by bjohare** [comment]
what about elements like 'text' that have a 'key' attribute but no 'value' attribute?

**Comment by bjohare** [comment]
'check' is the same..

**Comment by bgirardot** [comment]
text would have to just be a not null, any value.
check allows 3 outcomes:  k=yes, k=no, no k=v pair

**Comment by bjohare** [comment]
Ok will look at this now before we go live..

**Comment by bgirardot** [comment]
so maybe check is also just a not null

**Comment by bgirardot** [comment]
Here is the full spec for the presets file, I don't know how we could support all it with chunks and this and that. But I think the basic 4 types of presets would be good to try and support, key, text, combo, multiselect, check

https://josm.openstreetmap.de/wiki/TaggingPresets

**Comment by PaulUithol** [comment]
On how we use them: having those elements in the preset file (combo, check,
text, etc) means I want users to fill out these values. It's not that
restrictive though; especially when it comes to values, there are so many
(see for example amenity) that you'd just list the most common ones in the
combo to avoid spelling mistakes.

So in our case, the values for a combo are just the most often used ones.
You're still free to deviate if required - and I would want other values as
well. The column is there anyway, so I wouldn't see a reason for removing
other values? Text elements indicate a completely free field (like name);
therefore, I'd certainly want all values, always.

We also use keys containing double colons btw. Like addr:housenumber and
building:levels (both standard keys). Does that work with the more granular
key control?

what about elements like 'text' that have a 'key' attribute but no 'value'
attribute?

—
Reply to this email directly or view it on GitHub
<https://github.com/hotosm/osm-export-tool2/issues/74#issuecomment-145053327>
.

**Comment by bjohare** [comment]
Ok will aim to support those 5 elements you suggest. I will need to double check about the double colons but am using osmfilter whose syntax is key=value so should be ok in theory!

**Comment by bgirardot** [comment]
@Paul That is interesting. I guess we will have to decide how we want combo or multiselect handled, i would err on the side of "not null" if you don't think people are going to just want to find the one's that were in their preset value list. 

Maybe that is all we are getting from the preset files anyway, what keys they want in the outcome and the values don't mean much, we just want those keys selected regardless of the values.

**Comment by bjohare** [comment]
So what's the requirement? Select all values for the corresponding key?

**Comment by dodobas** [comment]
We need to differentiate between: export process that should gather all interesting keys and export all data, and filtering process which would remove data from the export.

Support for all available keys in the export process is what would be expected, however filtering is a feature with limited use cases, and it can be executed by any desktop GIS software.

We can only provide filters for SHP, SQLite and KMZ formats as all other formats are 'proietary' and expect certain feature value combinations.

Similarly, we need to be careful when applying *tag exclusion* for every format, as some might depend on a particular tag, which again limits us to SHP, SQLite and KMZ formats.

AFIAK, old export system kinda supported filtering if you used *Tag transform SQL files* and then handcraft SQL to delete unwanted data.

**Comment by PaulUithol** [comment]
I think so. I don't see the benefit of throwing out other values really,
once that key/column has been selected anyway. If you do want to limit to
another set of values, you can always do that in whatever software you're
processing it in next. But we are, for example, also using the attribute
table in QGis to find erroneous values in the whole dataset.

**Comment by PaulUithol** [comment]
What's the resolution that has been implemented here? Seems to me that once a key has been encountered in either a `key`, `text`, `combo`, `multiselect`, and `check` element, all values get exported now? Which is very much fine by me, but would be good to document.

**Comment by bjohare** [comment]
@PaulUithol yes that correct.

**Comment by mataharimhairi** [comment]
https://github.com/hotosm/osm-export-tool2/issues/84

**Comment by bdon** [comment]
I believe the ambiguity about tags has been resolved with the new YAML feature selection format; closing this issue.
