### ISSUE TITLE
OSM and HDM Data Models should support more tags

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#78]
The code which handles Tag generation using OSM and HDM data models should support tags with colons in them, eg addr:housenumber. This is currently not supported. If users need these tags in the export they should use a custom preset.

**Comment by bjohare** [comment]
Related to #77

**Comment by bjohare** [comment]
Added support for additional tags of the form, eg addr:housenumber

**Comment by d3netxer** [comment]
+1

**Comment by d3netxer** [comment]
@bjohare now that you Turned on 'attribute_name_laundering' in ogr ini file and updated thematic_shp utility in #77 is there still a need to support more tags?
