### ISSUE TITLE
Add copright and license notice to interface and downloads

### ISSUE THREAD

**Issue by bgirardot** [hotosm/osm-export-tool2#83]
We need to give the proper attribution and license notice for the data we are making available.

It was suggested that we put a notice like:

Data is copyright OpenStreetMap Contributors, ODbL 1.0 licensed

on the About Page, the export downloads page and in a file with the downloaded data as well.

Also some file formats like the garmin (mkgmap) should support embedding the copyright and license notice in the files themselves which we should do if possible.

Please see: https://wiki.osmfoundation.org/wiki/License#How_should_I_attribute_you.3F for the official details.

**Comment by bjohare** [comment]
Added license info to about and detail pages.

**Comment by mataharimhairi** [comment]
@bjohare Is it possible to add it to the 'About' page when a user is not logged in? Currently only on the 'About' page when user is signed in and on the 'Export Details' page.
