### ISSUE TITLE
Adjust HOT export regions to include several excluded countries in developing world

### ISSUE THREAD

**Issue by TylerRadford** [hotosm/osm-export-tool2#86]
HOT has worked in a number of countries that are currently outside the exportable regions. Suggest adjusting exportable regions to include:

Caribbean
Mexico
Pacific Island nations including US territories
Papua New Guinea
Southeast Asia countries
India - for discussion

At this point the request is only to include additional developing countries including those where HOT mapping has taken place, not the entire world.

**Comment by mataharimhairi** [comment]
@TylerRadford This is something Brian and I discussed on numerous occasions.  We also brought it up during a Technical WG meeting, but perhaps it should be proposed at the next Activation WG meeting? Or are you happy for me to go ahead and add the above regions straight away?

**Comment by bgirardot** [comment]
@mataharimhairi Could someone please document how to add and remove coverage areas for the new export tool.

**Comment by mataharimhairi** [comment]
@bgirardot definitely! this is already on the list of final documentation and reporting required for the project.

**Comment by bjohare** [comment]
Added a page to the [wiki](https://github.com/hotosm/osm-export-tool2/wiki/Add-a-HOT-Export-Region) describing the process of adding a HOT Export Region.

**Comment by TylerRadford** [comment]
@mataharimhairi after talking with @dodobas I believe we should go ahead with the change -- we no longer have infrastructure issues to worry about & this would benefit those working in/on the above mentioned areas.

**Comment by TylerRadford** [comment]
Can we pls add Mexico ASAP given the current activation. Thanks!

**Comment by dodobas** [comment]
added, also added @bgirardot and @bjohare along @mataharimhairi as 'admins' ... login though OSM and manually access /admin/ url

Simply create new region or modify existing one, it seems straight forward

**Comment by TylerRadford** [comment]
Thank you Drazen

**Comment by mataharimhairi** [comment]
@TylerRadford I have gone ahead and added the other regions requested:

Caribbean
Pacific Island nations including US territories
Papua New Guinea
Southeast Asia countries
India

**Comment by mataharimhairi** [comment]
@bjohare @dodobas I have also taken the liberty of deleting old region polygon and created merged new ones as it looks really messy and may miss out areas on the Export Tool.

**Comment by mataharimhairi** [comment]
@bjohare actually it appears that the exports are tied to regions. so if i try to delete a region it deletes all the associated jobs.

**Comment by bjohare** [comment]
@mataharimhairi yes, probably too tightly coupled in hindsight... there are a couple of alternative approaches:
1. prevent cascade delete of jobs when a region is deleted.. ie set the job's region to null.
2. don't link jobs to actual regions, just hold the region name as part of the job.

My preference is for 1 above as in the case of 2 we'll potentially end up with jobs with region names that don't exist on the system.. In the case of 1, jobs can be re-assigned to a new region if their old one is deleted. This can be done in the admin..

**Comment by TylerRadford** [comment]
Thanks for working on this guys. Since the regions now look messy and overlap in production, can you provide an update - are we able to make the fix easily to prevent cascade delete? Or remove the newly added regions until this is implemented?

**Comment by bjohare** [comment]
Am working on a fix for this at the moment, hope to have it finished on Friday. Have deleted the newly created India and Southeast Asian regions which had no associated exports. Also tidied up existing region boundaries to avoid overlaps.

**Comment by mataharimhairi** [comment]
@bjohare cheers for working on a fix and for removing/tidying up the regions. will wait till the new system is in place before adding the other regions.

**Comment by bjohare** [comment]
Added fix for this issue. Export jobs are no longer deleted when a region is deleted. See updated [documentation](https://github.com/hotosm/osm-export-tool2/wiki/Add-a-HOT-Export-Region) for possible workflow for managing new regions and assigning exports to newly created regions.

**Comment by mataharimhairi** [comment]
Cheers @bjohare! I have also added Greece as a region to the Export Tool as requested by MapAction. This has been authorised by Tyler as it is towards their efforts to assist the Syrian refugee crisis.

**Comment by bdon** [comment]
This migration doesn't seem to have been run in prod, and issue #106 as well as merging in changes from the ARC fork will resolve this issue. For this reason I've reverted the two commits related to #86 for now, will revisit when we tackle #106.
