### ISSUE TITLE
Write a chef or puppet configuration

### ISSUE THREAD

**Issue by Zverik** [hotosm/osm-export-tool2#87]
Installation is too hard. I've been installing packages and dependencies for an hour, and am still midway. And celery for some reason doesn't work. Django, it seems, is required, but not mentioned.

Please make a chef or puppet file, so one can install this export tool on a virtual machine with a few lines.

**Comment by mataharimhairi** [comment]
Please feel free to create one and add it to the repository, but keep in mind that several installation packages would have to be made to account for the various operating systems and versions. Plus they would have to be kept up-to-date.

**Comment by mojodna** [comment]
See https://github.com/americanredcross/osm-export-ops for an Ansible / Vagrant provisioning playbook.

**Comment by bdon** [comment]
I'm a big fan of http://packer.io + shell scripts for creating VMs for local development, and AMIs for AWS - depending on our hosting provider this could be a streamlined solution

**Comment by mojodna** [comment]
We Dockerized everything and provide a pair of `docker-compose` configuration files for both development and production deployment.

**Comment by Zverik** [comment]
Awesome, thanks!
