### ISSUE TITLE
Add a dedicated email to catch export task errors

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#88]
A hotosm email address is required to receive notifications of failed export tasks. Should be configurable as a setting.

**Comment by mataharimhairi** [comment]
@TylerRadford @dodobas would it be best to use a systems administrator email (not your personal one), that can be checked routinely?

**Comment by bjohare** [comment]
The newly added TASK_ERROR_EMAIL setting is currently blank and should be set when an email address is set up. Celery workers should be restarted on next release to pick up changes to export tasks.

**Comment by dodobas** [comment]
created a dedicated restricted 'export-tool@hotosm.org' group to collect any errors that might happen

ask me if you want access
