### ISSUE TITLE
Add hotosm-piwik tracker to the site

### ISSUE THREAD

**Issue by dodobas** [hotosm/osm-export-tool2#90]
We want to track visitors of http://export.hotosm.org using piwik when deployed in production

**Comment by mataharimhairi** [comment]
Has this been implemented? Just following up on the issues.

**Comment by bdon** [comment]
There currently is not a tracker included on the site. If HOT already has a piwik, it should be simple to drop in the tracker.

**Comment by mataharimhairi** [comment]
There is a HOT piwik [1] - the new Export tool just has to be added.

[1] https://piwik.hotosm.org/index.php?

**Comment by mataharimhairi** [comment]
@dodobas could you please provide us access to piwik

**Comment by cgiovando** [comment]
No, unfortunately no reply from @dodobas - I'll email him again today, but otherwise we may have to go with a fresh Piwik install.

cc @david-hotosm

**Comment by bdon** [comment]
I added a piwik "Website" for the export tool v3 prod. Since our app is single-page we may need React-Router middleware to properly track internal navigation.

**Comment by mojodna** [comment]
https://github.com/joernroeder/piwik-react-router
