### ISSUE TITLE
Need a contact email address for user error reporting

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#91]
We should have a contact email address for users to report failing tasks or general errors / questions.

**Comment by bjohare** [comment]
exports@hotosm.org?

**Comment by dodobas** [comment]
created a dedicated restricted 'export-tool@hotosm.org' group to collect any errors that might happen

ask me if you want access

**Comment by bjohare** [comment]
Added export-tool@hotosm.org to TASK_ERROR_EMAIL setting.

**Comment by mataharimhairi** [comment]
@bjohare ho has access to these error emails? Are they directed to the system administrator @dodobas?
