### ISSUE TITLE
Export runs that fail completely not reported in UI correctly

### ISSUE THREAD

**Issue by bjohare** [hotosm/osm-export-tool2#92]

**Comment by thomas-maschler** [comment]
Confirming this. I used a corrupted preset file and export wouldn't start. Just got a spinning wheel.

**Comment by bjohare** [comment]
Thanks Thomas. Fixed this on export detail page. Think the error you reported has to do with #95 which I've also fixed. These fixes will appear in the next release.. not sure when that is. You can review these changes at http://hot.geoweb.io/
