### ISSUE TITLE
API TOKEN REQUEST

### ISSUE THREAD

**Issue by thomas-maschler** [hotosm/osm-export-tool2#96]
Referring to Brian's comment in crowdcover/logging-roads#49 I'd like to request a token for nightly extract for our logging road project.

Thanks

**Comment by mataharimhairi** [comment]
@thomas-maschler have you received the API token from @bjohare yet?

**Comment by thomas-maschler** [comment]
Yes. All good. Thanks



On Wed, Nov 4, 2015 at 9:21 PM -0800, "mataharimhairi" <notifications@github.com<mailto:notifications@github.com>> wrote:


@thomas-maschler<https://github.com/thomas-maschler> have you received the API token from @bjohare<https://github.com/bjohare> yet?

-

**Comment by mataharimhairi** [comment]
Great @thomas-maschler. Will close this issue :)
