### ISSUE TITLE
export details preview image incorrect

### ISSUE THREAD

**Issue by govvin** [hotosm/osm-export-tool2#98]
I am testing the new export tool, and created an export job for the Philippines: http://export.hotosm.org/en/exports/9ef1948e-14dd-42d2-975f-bb469c5151ad/

The preview image for the job incorrectly displays the area of Thailand/India/Pacific ocean, instead of the expected area of interest, the Philippines. Below is a screenie: 
![screenshot](http://www.zimagez.com/full/c139df9ce5e8455f817defaa1cf6b754aef0d82a1431c5556924c0fb25bf0a9d7a971d975c8a5fb3cc91ac41599cc8e6373c19c3d88eba72.php)

**Comment by bgirardot** [comment]
Thank you very much for letting us know.
I think the linked to image is not displaying properly, could you drag and drop it in the text window here?

**Comment by gitGOwin** [comment]
Sorry about that. Image in the post displays properly from my end.

But try this link instead: http://en.zimagez.com/zimage/screenshot-181015-101902.php

**Comment by bjohare** [comment]
Not sure what the problem is there.. looks ok to me? http://export.hotosm.org/en/exports/9ef1948e-14dd-42d2-975f-bb469c5151ad/

**Comment by gitGOwin** [comment]
Hi @bjohare . 

From my end,  what I see is a preview  of Thailand/India/Pacific Ocean not my area of interest, which is the Philippines. Are you saying, you're seeing the overview map of the Philippines instead?

**Comment by bjohare** [comment]
Yes I see the Philippines..What happens if you refresh the page?

**Comment by gitGOwin** [comment]
Even after a refresh, I still see the same thing.

**Comment by mataharimhairi** [comment]
I tried to take a look at the preview map for the export but seems it no longer exists. Could you please confirm if this issue was addressed @govvin or is it still displaying the wrong location?

**Comment by govvin** [comment]
@mataharimhairi , thanks for keeping tabs on this. It appears that the original job has been deleted, so I made a job here, which is still running: http://export.hotosm.org/en/exports/e8223714-100f-47f2-827c-f2e34333fd84/

Looks like the original issue is no longer a problem, and the map preview now correctly displays the map of the Philippines.
