### ISSUE TITLE
The name field is missing in the shapefiles

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-export-tool2#99]
Seems the name field has been forgotten in the shapefilesmade through the OSM scheme, both the generic and thematic ones, despite it is obviously a must-have field for any extract.

**Comment by bjohare** [comment]
See http://hot.geoweb.io/en/exports/45ac35c7-25f0-4024-ba5f-d09b54f1d009/ for fix (HDM Model) or http://hot.geoweb.io/en/exports/85818a60-8f92-4df4-ad4b-aa263965a9d9/ OSm Model.

**Comment by severinmenard** [comment]
looks good, but I find another unexpected result (see next issue)

**Comment by severinmenard** [comment]
Oh, your dev instance has a very old database (like more than 2 months) but this is not the case for the production one, right?

**Comment by dodobas** [comment]
it has been deployed
